vim.cmd('colorscheme vague')

local bg = VagueColors.bg

vim.api.nvim_set_hl(0, 'WinSeparator', { bg = bg, fg = '#4b4848' })

vim.api.nvim_set_hl(0, '@function.method.call', { link = 'Function' })
vim.api.nvim_set_hl(0, '@function.call', { link = 'Function' })
vim.api.nvim_set_hl(0, '@variable.parameter', { link = '@variable' })
vim.api.nvim_set_hl(0, '@keyword.import', { link = '@keyword' })
vim.api.nvim_set_hl(0, '@variable.member', { link = '@variable' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#a4bac1' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = 'Grey70', bold = true })

vim.api.nvim_set_hl(0, 'Tag', { fg = '#cdc09e' })

vim.api.nvim_set_hl(0, 'CursorLine', { bg = bg, underline = false })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = VagueColors.number, bold = true })

vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = VagueColors.hint, bg = '' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = VagueColors.info, bg = '' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = VagueColors.warning, bg = '' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = VagueColors.error, bg = '' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#9f9f9f', bg = '' })

-- Don't set fg so syntax highlighting is kept
vim.api.nvim_set_hl(0, 'Visual', { bg = VagueColors.visual })
vim.api.nvim_set_hl(0, 'IncSearch', { link = 'Visual' })
vim.api.nvim_set_hl(0, 'Search', { link = 'Visual' })
vim.api.nvim_set_hl(0, 'CurSearch', { link = 'Visual' })

vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#9c9898' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = VagueColors.visual })

vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { link = 'String' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { link = 'Keyword' })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { link = 'Type' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { link = 'Function' })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { link = 'Number' })

-- Blink.cmp colors
vim.api.nvim_set_hl(0, 'BlinkCmpLabelMatch', { link = 'String' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindClass', { link = 'Type' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindEnum', { link = 'Type' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindInterface', { link = 'Type' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindStruct', { link = 'type' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindField', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindKeyword', { link = 'Keyword' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindMethod', { link = 'Function' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindFunction', { link = 'Function' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindEnumMember', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindConstant', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindText', { link = 'Comment' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindProperty', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindUnit', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindFile', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindValue', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindColor', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindEvent', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindModule', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindFolder', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindSnippet', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindVariable', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindOperator', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindReference', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindConstructor', { link = 'Variable' })
vim.api.nvim_set_hl(0, 'BlinkCmpKindTypeParameter', { link = 'Variable' })

local treesitterContextBG = '#3c4144'
vim.api.nvim_set_hl(0, 'TreesitterContext', { bg = treesitterContextBG })
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', { bg = treesitterContextBG })
vim.api.nvim_set_hl(0, 'WinBar', { bg = '#2e3232' })

vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', { fg = '#b5ba99', bold = true })
vim.api.nvim_set_hl(0, 'LspReferenceText', { link = 'Visual' })

vim.api.nvim_set_hl(0, 'EndOfBuffer', { bg = bg, fg = bg })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#cad2a5' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { link = 'Keyword' })

vim.api.nvim_set_hl(0, 'Error', { fg = VagueColors.error, bold = false })
vim.api.nvim_set_hl(0, 'ErrorMsg', { link = 'Error' })

vim.api.nvim_set_hl(0, 'FzfLuaHeaderText', { link = 'Error' })
vim.api.nvim_set_hl(0, 'FzfLuaLiveSym', { link = 'Error' })
vim.api.nvim_set_hl(0, 'FzfLuaBufFlagCur', { link = 'Error' })
vim.api.nvim_set_hl(0, 'FzfLuaPathLineNr', { link = 'String' })

vim.api.nvim_set_hl(0, 'DiffAdd', { fg = '#939a74' })
vim.api.nvim_set_hl(0, 'DiffAdded', { link = 'DiffAdd' })
vim.api.nvim_set_hl(0, '@diff.plus', { link = 'DiffAdd' })
vim.api.nvim_set_hl(0, 'DiffText', { fg = '#000000', bg = VagueColors.func })

vim.api.nvim_set_hl(0, 'MatchParen', { fg = '#d5d7d8', bold = true })

vim.api.nvim_set_hl(0, '@spell.gitcommit', { link = 'String' })
vim.api.nvim_set_hl(0, '@markup.heading.gitcommit', { link = 'Function' })
vim.api.nvim_set_hl(0, '@markup.link.gitcommit', { link = 'Number' })
vim.api.nvim_set_hl(0, '@string.special.path.gitcommit', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'fugitiveSymbolicRef', { link = 'Number' })

vim.api.nvim_set_hl(0, 'TelescopeMatching', { link = 'CursorLineNr' })
vim.api.nvim_set_hl(0, 'TelescopeMatchingAlternate', { link = 'Number' })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { link = 'Visual' })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { link = 'Function' })

vim.api.nvim_set_hl(0, 'DevIconPhp', { link = 'Function' })
vim.api.nvim_set_hl(0, 'DevIconH', { link = 'Keyword' })
vim.api.nvim_set_hl(0, 'DevIconCpp', { link = 'Function' })

vim.api.nvim_set_hl(0, 'FlashLabel', { fg = '#ffffff', bold = true })

vim.cmd('hi QuickfixLine gui=NONE')

-- Terminal color settings
vim.g.terminal_color_1 = '#be8c8c' -- Red
vim.g.terminal_color_2 = '#9da380' -- Green
vim.g.terminal_color_3 = '#c2ac7b' -- Yellow
vim.g.terminal_color_4 = '#90a0a5' -- Blue
vim.g.terminal_color_12 = '#90a0a5' -- Bright Blue
vim.g.terminal_color_5 = '#905858' -- Magenta (I hate it, make it red)

-- All highlights below to make them available as buffer completions
-- SpecialKey     xxx guifg=#acacac
-- EndOfBuffer    xxx guifg=#2b2e2f guibg=#2b2e2f
-- TermCursor     xxx cterm=reverse gui=reverse
-- NonText        xxx guifg=#acacac
-- Directory      xxx ctermfg=14 guifg=#a6a4a4
-- ErrorMsg       xxx links to Error
-- IncSearch      xxx links to Visual
-- Search         xxx links to Visual
-- CurSearch      xxx links to Visual
-- MoreMsg        xxx ctermfg=14 gui=bold guifg=#c0a3a5
-- ModeMsg        xxx ctermfg=10 guifg=#9da380
-- LineNr         xxx guifg=#9f9f9f
-- LineNrAbove    xxx links to LineNr
-- LineNrBelow    xxx links to LineNr
-- CursorLineNr   xxx cterm=bold gui=bold guifg=#dacaa5
-- CursorLineSign xxx links to SignColumn
-- CursorLineFold xxx links to FoldColumn
-- Question       xxx ctermfg=14 guifg=#c4aaa9
-- StatusLine     xxx cterm=reverse guifg=#c7c6c6 guibg=#1c1c24
-- StatusLineNC   xxx cterm=bold,underline guifg=#acacac
-- WinSeparator   xxx guifg=#4b4848 guibg=#2b2e2f
-- VertSplit      xxx links to WinSeparator
-- Title          xxx cterm=bold guifg=#c7c7d4
-- Visual         xxx guibg=#51575d
-- VisualNC       xxx cleared
-- WarningMsg     xxx ctermfg=11 gui=bold guifg=#c2ac7b
-- WildMenu       xxx guifg=#2b2e2f guibg=#c0a3a5
-- Folded         xxx guifg=#acacac guibg=#282830
-- FoldColumn     xxx guifg=#acacac guibg=#2b2e2f
-- DiffAdd        xxx guifg=#939a74
-- DiffChange     xxx guibg=#504b42
-- DiffDelete     xxx cterm=bold ctermfg=9 guibg=#4e4443
-- DiffText       xxx guifg=#000000 guibg=#c0a3a5
-- DiffTextAdd    xxx links to DiffText
-- SignColumn     xxx guifg=#c7c6c6 guibg=#2b2e2f
-- Conceal        xxx guifg=#c0a3a5
-- SpellBad       xxx cterm=undercurl gui=undercurl
-- SpellCap       xxx cterm=undercurl gui=undercurl
-- SpellRare      xxx cterm=undercurl gui=undercurl
-- SpellLocal     xxx cterm=undercurl gui=undercurl
-- Pmenu          xxx cterm=reverse guifg=#c7c6c6
-- PmenuSel       xxx guibg=#51575d
-- PmenuMatch     xxx cterm=bold gui=bold
-- PmenuMatchSel  xxx cterm=bold gui=bold
-- PmenuKind      xxx links to Pmenu
-- PmenuKindSel   xxx links to PmenuSel
-- PmenuExtra     xxx links to Pmenu
-- PmenuExtraSel  xxx links to PmenuSel
-- PmenuSbar      xxx links to Pmenu
-- PmenuThumb     xxx guibg=#9c9898
-- PmenuBorder    xxx guifg=#878787
-- TabLine        xxx guifg=#c7c6c6 guibg=#282830
-- TabLineSel     xxx guifg=#2b2e2f guibg=#c7c6c6
-- TabLineFill    xxx guifg=#acacac guibg=#282830
-- CursorColumn   xxx guibg=#282830
-- CursorLine     xxx guibg=#2b2e2f
-- ColorColumn    xxx cterm=reverse guibg=#282830
-- QuickFixLine   xxx ctermfg=14 guifg=#c0a3a5
-- Whitespace     xxx guifg=#282830
-- NormalNC       xxx cleared
-- MsgSeparator   xxx gui=bold guifg=#9da380 guibg=#282830
-- NormalFloat    xxx guifg=#c7c6c6 guibg=#2b2e2f
-- MsgArea        xxx cleared
-- FloatBorder    xxx guifg=#878787 guibg=#2b2e2f
-- WinBar         xxx cterm=bold guifg=#c7c6c6 guibg=#1c1c24
-- WinBarNC       xxx cterm=bold guifg=#acacac
-- Cursor         xxx guifg=bg guibg=fg
-- FloatTitle     xxx guifg=#878787 guibg=#2b2e2f
-- FloatFooter    xxx guifg=#878787 guibg=#2b2e2f
-- StatusLineTerm xxx guifg=#c7c6c6 guibg=#1c1c24
-- StatusLineTermNC xxx guifg=#acacac
-- StderrMsg      xxx links to ErrorMsg
-- StdoutMsg      xxx cleared
-- OkMsg          xxx ctermfg=10 guifg=#8faf77
-- PreInsert      xxx links to Added
-- RedrawDebugNormal xxx cterm=reverse gui=reverse
-- Underlined     xxx cterm=underline gui=underline
-- lCursor        xxx guifg=bg guibg=fg
-- CursorIM       xxx links to Cursor
-- PmenuShadowThrough xxx links to FloatShadowThrough
-- FloatShadowThrough xxx ctermbg=0 guibg=NvimDarkGrey4 blend=100
-- Added          xxx ctermfg=10 guifg=#8faf77
-- ComplMatchIns  xxx cleared
-- ComplHint      xxx links to NonText
-- ComplHintMore  xxx links to MoreMsg
-- Substitute     xxx guifg=#a1b3b9 guibg=#51575d
-- VisualNOS      xxx gui=underline guibg=#acacac
-- Normal         xxx guifg=#c7c6c6 guibg=#2b2e2f
-- Character      xxx guifg=#9da380
-- Constant       xxx guifg=#c4aaa9
-- Number         xxx guifg=#dacaa5
-- Boolean        xxx guifg=#dacaa5
-- Float          xxx guifg=#dacaa5
-- Conditional    xxx guifg=#8cadc6
-- Statement      xxx cterm=bold guifg=#8cadc6
-- Repeat         xxx guifg=#8cadc6
-- Label          xxx guifg=#8cadc6
-- Keyword        xxx guifg=#8cadc6
-- Exception      xxx guifg=#8cadc6
-- Include        xxx guifg=#8cadc6
-- PreProc        xxx guifg=#c4aaa9
-- Define         xxx guifg=#acacac
-- Macro          xxx guifg=#c4aaa9
-- PreCondit      xxx guifg=#acacac
-- StorageClass   xxx guifg=#c4aaa9
-- Type           xxx guifg=#a1b3b9
-- Structure      xxx guifg=#c4aaa9
-- Typedef        xxx guifg=#c4aaa9
-- Tag            xxx guifg=#cdc09e
-- Special        xxx ctermfg=14 guifg=#a3b8b6
-- SpecialChar    xxx guifg=#8cadc6
-- SpecialComment xxx guifg=#8cadc6
-- Debug          xxx guifg=#c4aaa9
-- Ignore         xxx links to Normal
-- LspCodeLens    xxx guifg=#acacac
-- LspCodeLensSeparator xxx guifg=#acacac
-- LspInlayHint   xxx links to NonText
-- LspReferenceRead xxx guibg=#acacac
-- LspReferenceText xxx guibg=#acacac
-- LspReferenceWrite xxx guibg=#acacac
-- LspReferenceTarget xxx links to LspReferenceText
-- LspSignatureActiveParameter xxx cterm=bold gui=bold guifg=#b5ba99
-- SnippetTabstop xxx links to Visual
-- SnippetTabstopActive xxx links to SnippetTabstop
-- DiagnosticFloatingError xxx links to DiagnosticError
-- DiagnosticError xxx guifg=#dc9e92
-- DiagnosticFloatingWarn xxx links to DiagnosticWarn
-- DiagnosticWarn xxx guifg=#c2ac7b
-- DiagnosticFloatingInfo xxx links to DiagnosticInfo
-- DiagnosticInfo xxx guifg=#a6a4a4
-- DiagnosticFloatingHint xxx links to DiagnosticHint
-- DiagnosticHint xxx guifg=#a6a4a4
-- DiagnosticFloatingOk xxx links to DiagnosticOk
-- DiagnosticOk   xxx ctermfg=10 guifg=#8faf77
-- DiagnosticVirtualTextError xxx gui=bold guifg=#dc9e92
-- DiagnosticVirtualTextWarn xxx gui=bold guifg=#c2ac7b
-- DiagnosticVirtualTextInfo xxx gui=italic guifg=#c4aaa9
-- DiagnosticVirtualTextHint xxx guifg=#a6a4a4
-- DiagnosticVirtualTextOk xxx guifg=#8faf77
-- DiagnosticVirtualLinesError xxx links to DiagnosticError
-- DiagnosticVirtualLinesWarn xxx links to DiagnosticWarn
-- DiagnosticVirtualLinesInfo xxx links to DiagnosticInfo
-- DiagnosticVirtualLinesHint xxx links to DiagnosticHint
-- DiagnosticVirtualLinesOk xxx links to DiagnosticOk
-- DiagnosticSignError xxx links to DiagnosticError
-- DiagnosticSignWarn xxx links to DiagnosticWarn
-- DiagnosticSignInfo xxx links to DiagnosticInfo
-- DiagnosticSignHint xxx links to DiagnosticHint
-- DiagnosticSignOk xxx links to DiagnosticOk
-- DiagnosticUnnecessary xxx links to Comment
-- Comment        xxx guifg=#acacac
-- @variable      xxx guifg=#c7c6c6
-- @variable.builtin xxx guifg=#a3b8b6
-- @variable.parameter xxx links to @variable
-- @variable.parameter.builtin xxx links to Special
-- @constant      xxx guifg=#c4aaa9
-- @constant.builtin xxx guifg=#dacaa5
-- @module        xxx guifg=#c4aaa9
-- @module.builtin xxx links to Special
-- @label         xxx guifg=#8cadc6
-- @string        xxx guifg=#9da380
-- String         xxx ctermfg=10 guifg=#9da380
-- @string.regexp xxx guifg=#8cadc6
-- @string.special xxx links to SpecialChar
-- @string.escape xxx guifg=#8cadc6
-- @string.special.url xxx guifg=#c0a3a5
-- @character     xxx guifg=#9da380
-- @character.special xxx guifg=#8cadc6
-- @boolean       xxx guifg=#dacaa5
-- @number        xxx guifg=#dacaa5
-- @number.float  xxx guifg=#dacaa5
-- @type          xxx guifg=#a1b3b9
-- @type.builtin  xxx guifg=#a3b8b6
-- @attribute     xxx guifg=#c4aaa9
-- @attribute.builtin xxx links to Special
-- @property      xxx guifg=#c7c7d4
-- Identifier     xxx ctermfg=12 guifg=#c4aaa9
-- @function      xxx guifg=#c0a3a5
-- Function       xxx ctermfg=14 guifg=#c0a3a5
-- @function.builtin xxx guifg=#c0a3a5
-- @constructor   xxx guifg=#c4aaa9
-- @operator      xxx guifg=#96a3b2
-- Operator       xxx guifg=#96a3b2
-- @keyword       xxx guifg=#8cadc6
-- @punctuation   xxx links to Delimiter
-- Delimiter      xxx guifg=#c7c6c6
-- @punctuation.special xxx guifg=#8cadc6
-- @comment       xxx links to Comment
-- @comment.error xxx links to DiagnosticError
-- @comment.warning xxx links to DiagnosticWarn
-- @comment.note  xxx links to DiagnosticInfo
-- @comment.todo  xxx links to Todo
-- Todo           xxx cterm=bold guifg=#c0a3a5
-- @markup        xxx guifg=#c7c6c6
-- @markup.strong xxx cterm=bold gui=bold guifg=#c7c6c6
-- @markup.italic xxx cterm=italic gui=italic guifg=#c7c6c6
-- @markup.strikethrough xxx cterm=strikethrough gui=strikethrough guifg=#acacac
-- @markup.underline xxx cterm=underline gui=underline guifg=#c7c6c6
-- @markup.heading xxx gui=bold guifg=#8cadc6
-- @markup.link   xxx guifg=#9da380
-- @diff          xxx cleared
-- @diff.plus     xxx links to DiffAdd
-- @diff.minus    xxx guibg=#4e4443
-- Removed        xxx ctermfg=9 guifg=#dc9e92
-- @diff.delta    xxx guibg=#504b42
-- Changed        xxx ctermfg=14 guifg=#e6be8c
-- @tag           xxx links to Tag
-- @tag.builtin   xxx links to Special
-- @markup.heading.1.delimiter.vimdoc xxx cterm=underdouble,nocombine gui=underdouble,nocombine guifg=bg guibg=bg guisp=fg
-- @markup.heading.2.delimiter.vimdoc xxx cterm=underline,nocombine gui=underline,nocombine guifg=bg guibg=bg guisp=fg
-- @lsp           xxx cleared
-- @lsp.type.class xxx guifg=#c4aaa9
-- @lsp.type.comment xxx guifg=#acacac
-- @lsp.type.decorator xxx links to @attribute
-- @lsp.type.enum xxx guifg=#c4aaa9
-- @lsp.type.enumMember xxx guifg=#a3b8b6
-- @lsp.type.event xxx links to @type
-- @lsp.type.function xxx guifg=#b9a3ba
-- @lsp.type.interface xxx guifg=#c4aaa9
-- @lsp.type.keyword xxx links to @keyword
-- @lsp.type.macro xxx guifg=#c4aaa9
-- @lsp.type.method xxx links to @function.method
-- @lsp.type.modifier xxx links to @type.qualifier
-- @lsp.type.namespace xxx guifg=#c4aaa9
-- @lsp.type.number xxx links to @number
-- @lsp.type.operator xxx links to @operator
-- @lsp.type.parameter xxx guifg=#b9a3ba
-- @lsp.type.property xxx guifg=#a1b3b9
-- @lsp.type.regexp xxx links to @string.regexp
-- @lsp.type.string xxx links to @string
-- @lsp.type.struct xxx links to @type
-- @lsp.type.type xxx links to @type
-- @lsp.type.typeParameter xxx guifg=#c4aaa9
-- @type.definition xxx guifg=#c4aaa9
-- @lsp.type.variable xxx guifg=#c4aaa9
-- @lsp.mod.deprecated xxx links to DiagnosticDeprecated
-- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=NvimLightRed
-- FloatShadow    xxx ctermbg=0 guibg=NvimDarkGrey4 blend=80
-- MatchParen     xxx cterm=bold gui=bold guifg=#d5d7d8
-- PmenuShadow    xxx ctermbg=0 guibg=NvimDarkGrey4 blend=100
-- RedrawDebugClear xxx ctermfg=0 ctermbg=11 guibg=NvimDarkYellow
-- RedrawDebugComposed xxx ctermfg=0 ctermbg=10 guibg=NvimDarkGreen
-- RedrawDebugRecompose xxx ctermfg=0 ctermbg=9 guibg=NvimDarkRed
-- Error          xxx guifg=#dc9e92
-- DiagnosticUnderlineError xxx cterm=underline gui=undercurl guisp=#dc9e92
-- DiagnosticUnderlineWarn xxx cterm=underline gui=undercurl guisp=#e6be8c
-- DiagnosticUnderlineInfo xxx cterm=underline gui=undercurl guisp=#c4aaa9
-- DiagnosticUnderlineHint xxx cterm=underline gui=undercurl guisp=#a6a4a4
-- DiagnosticUnderlineOk xxx cterm=underline gui=undercurl guisp=#8faf77
-- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
-- NvimAssignment xxx links to Operator
-- NvimPlainAssignment xxx links to NvimAssignment
-- NvimAugmentedAssignment xxx links to NvimAssignment
-- NvimAssignmentWithAddition xxx links to NvimAugmentedAssignment
-- NvimAssignmentWithSubtraction xxx links to NvimAugmentedAssignment
-- NvimAssignmentWithConcatenation xxx links to NvimAugmentedAssignment
-- NvimOperator   xxx links to Operator
-- NvimUnaryOperator xxx links to NvimOperator
-- NvimUnaryPlus  xxx links to NvimUnaryOperator
-- NvimUnaryMinus xxx links to NvimUnaryOperator
-- NvimNot        xxx links to NvimUnaryOperator
-- NvimBinaryOperator xxx links to NvimOperator
-- NvimComparison xxx links to NvimBinaryOperator
-- NvimComparisonModifier xxx links to NvimComparison
-- NvimBinaryPlus xxx links to NvimBinaryOperator
-- NvimBinaryMinus xxx links to NvimBinaryOperator
-- NvimConcat     xxx links to NvimBinaryOperator
-- NvimConcatOrSubscript xxx links to NvimConcat
-- NvimOr         xxx links to NvimBinaryOperator
-- NvimAnd        xxx links to NvimBinaryOperator
-- NvimMultiplication xxx links to NvimBinaryOperator
-- NvimDivision   xxx links to NvimBinaryOperator
-- NvimMod        xxx links to NvimBinaryOperator
-- NvimTernary    xxx links to NvimOperator
-- NvimTernaryColon xxx links to NvimTernary
-- NvimParenthesis xxx links to Delimiter
-- NvimLambda     xxx links to NvimParenthesis
-- NvimNestingParenthesis xxx links to NvimParenthesis
-- NvimCallingParenthesis xxx links to NvimParenthesis
-- NvimSubscript  xxx links to NvimParenthesis
-- NvimSubscriptBracket xxx links to NvimSubscript
-- NvimSubscriptColon xxx links to NvimSubscript
-- NvimCurly      xxx links to NvimSubscript
-- NvimContainer  xxx links to NvimParenthesis
-- NvimDict       xxx links to NvimContainer
-- NvimList       xxx links to NvimContainer
-- NvimIdentifier xxx links to Identifier
-- NvimIdentifierScope xxx links to NvimIdentifier
-- NvimIdentifierScopeDelimiter xxx links to NvimIdentifier
-- NvimIdentifierName xxx links to NvimIdentifier
-- NvimIdentifierKey xxx links to NvimIdentifier
-- NvimColon      xxx links to Delimiter
-- NvimComma      xxx links to Delimiter
-- NvimArrow      xxx links to Delimiter
-- NvimRegister   xxx links to SpecialChar
-- NvimNumber     xxx links to Number
-- NvimFloat      xxx links to NvimNumber
-- NvimNumberPrefix xxx links to Type
-- NvimOptionSigil xxx links to Type
-- NvimOptionName xxx links to NvimIdentifier
-- NvimOptionScope xxx links to NvimIdentifierScope
-- NvimOptionScopeDelimiter xxx links to NvimIdentifierScopeDelimiter
-- NvimEnvironmentSigil xxx links to NvimOptionSigil
-- NvimEnvironmentName xxx links to NvimIdentifier
-- NvimString     xxx links to String
-- NvimStringBody xxx links to NvimString
-- NvimStringQuote xxx links to NvimString
-- NvimStringSpecial xxx links to SpecialChar
-- NvimSingleQuote xxx links to NvimStringQuote
-- NvimSingleQuotedBody xxx links to NvimStringBody
-- NvimSingleQuotedQuote xxx links to NvimStringSpecial
-- NvimDoubleQuote xxx links to NvimStringQuote
-- NvimDoubleQuotedBody xxx links to NvimStringBody
-- NvimDoubleQuotedEscape xxx links to NvimStringSpecial
-- NvimFigureBrace xxx links to NvimInternalError
-- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
-- NvimSpacing    xxx links to Normal
-- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
-- NvimInvalid    xxx links to Error
-- NvimInvalidAssignment xxx links to NvimInvalid
-- NvimInvalidPlainAssignment xxx links to NvimInvalidAssignment
-- NvimInvalidAugmentedAssignment xxx links to NvimInvalidAssignment
-- NvimInvalidAssignmentWithAddition xxx links to NvimInvalidAugmentedAssignment
-- NvimInvalidAssignmentWithSubtraction xxx links to NvimInvalidAugmentedAssignment
-- NvimInvalidAssignmentWithConcatenation xxx links to NvimInvalidAugmentedAssignment
-- NvimInvalidOperator xxx links to NvimInvalid
-- NvimInvalidUnaryOperator xxx links to NvimInvalidOperator
-- NvimInvalidUnaryPlus xxx links to NvimInvalidUnaryOperator
-- NvimInvalidUnaryMinus xxx links to NvimInvalidUnaryOperator
-- NvimInvalidNot xxx links to NvimInvalidUnaryOperator
-- NvimInvalidBinaryOperator xxx links to NvimInvalidOperator
-- NvimInvalidComparison xxx links to NvimInvalidBinaryOperator
-- NvimInvalidComparisonModifier xxx links to NvimInvalidComparison
-- NvimInvalidBinaryPlus xxx links to NvimInvalidBinaryOperator
-- NvimInvalidBinaryMinus xxx links to NvimInvalidBinaryOperator
-- NvimInvalidConcat xxx links to NvimInvalidBinaryOperator
-- NvimInvalidConcatOrSubscript xxx links to NvimInvalidConcat
-- NvimInvalidOr  xxx links to NvimInvalidBinaryOperator
-- NvimInvalidAnd xxx links to NvimInvalidBinaryOperator
-- NvimInvalidMultiplication xxx links to NvimInvalidBinaryOperator
-- NvimInvalidDivision xxx links to NvimInvalidBinaryOperator
-- NvimInvalidMod xxx links to NvimInvalidBinaryOperator
-- NvimInvalidTernary xxx links to NvimInvalidOperator
-- NvimInvalidTernaryColon xxx links to NvimInvalidTernary
-- NvimInvalidDelimiter xxx links to NvimInvalid
-- NvimInvalidParenthesis xxx links to NvimInvalidDelimiter
-- NvimInvalidLambda xxx links to NvimInvalidParenthesis
-- NvimInvalidNestingParenthesis xxx links to NvimInvalidParenthesis
-- NvimInvalidCallingParenthesis xxx links to NvimInvalidParenthesis
-- NvimInvalidSubscript xxx links to NvimInvalidParenthesis
-- NvimInvalidSubscriptBracket xxx links to NvimInvalidSubscript
-- NvimInvalidSubscriptColon xxx links to NvimInvalidSubscript
-- NvimInvalidCurly xxx links to NvimInvalidSubscript
-- NvimInvalidContainer xxx links to NvimInvalidParenthesis
-- NvimInvalidDict xxx links to NvimInvalidContainer
-- NvimInvalidList xxx links to NvimInvalidContainer
-- NvimInvalidValue xxx links to NvimInvalid
-- NvimInvalidIdentifier xxx links to NvimInvalidValue
-- NvimInvalidIdentifierScope xxx links to NvimInvalidIdentifier
-- NvimInvalidIdentifierScopeDelimiter xxx links to NvimInvalidIdentifier
-- NvimInvalidIdentifierName xxx links to NvimInvalidIdentifier
-- NvimInvalidIdentifierKey xxx links to NvimInvalidIdentifier
-- NvimInvalidColon xxx links to NvimInvalidDelimiter
-- NvimInvalidComma xxx links to NvimInvalidDelimiter
-- NvimInvalidArrow xxx links to NvimInvalidDelimiter
-- NvimInvalidRegister xxx links to NvimInvalidValue
-- NvimInvalidNumber xxx links to NvimInvalidValue
-- NvimInvalidFloat xxx links to NvimInvalidNumber
-- NvimInvalidNumberPrefix xxx links to NvimInvalidNumber
-- NvimInvalidOptionSigil xxx links to NvimInvalidIdentifier
-- NvimInvalidOptionName xxx links to NvimInvalidIdentifier
-- NvimInvalidOptionScope xxx links to NvimInvalidIdentifierScope
-- NvimInvalidOptionScopeDelimiter xxx links to NvimInvalidIdentifierScopeDelimiter
-- NvimInvalidEnvironmentSigil xxx links to NvimInvalidOptionSigil
-- NvimInvalidEnvironmentName xxx links to NvimInvalidIdentifier
-- NvimInvalidString xxx links to NvimInvalidValue
-- NvimInvalidStringBody xxx links to NvimStringBody
-- NvimInvalidStringQuote xxx links to NvimInvalidString
-- NvimInvalidStringSpecial xxx links to NvimStringSpecial
-- NvimInvalidSingleQuote xxx links to NvimInvalidStringQuote
-- NvimInvalidSingleQuotedBody xxx links to NvimInvalidStringBody
-- NvimInvalidSingleQuotedQuote xxx links to NvimInvalidStringSpecial
-- NvimInvalidDoubleQuote xxx links to NvimInvalidStringQuote
-- NvimInvalidDoubleQuotedBody xxx links to NvimInvalidStringBody
-- NvimInvalidDoubleQuotedEscape xxx links to NvimInvalidStringSpecial
-- NvimInvalidDoubleQuotedUnknownEscape xxx links to NvimInvalidValue
-- NvimInvalidFigureBrace xxx links to NvimInvalidDelimiter
-- NvimInvalidSpacing xxx links to ErrorMsg
-- NvimDoubleQuotedUnknownEscape xxx links to NvimInvalidValue
-- NvimTreeStatusLine xxx cleared
-- GrugFarVisualBufrange xxx links to Visual
-- GrugFarResultsLongLineStr xxx links to Comment
-- GrugFarHelpWinActionText xxx links to ModeMsg
-- GrugFarHelpWinActionPrefix xxx links to Title
-- GrugFarHelpWinHeader xxx links to Title
-- GrugFarHelpHeaderKey xxx links to Identifier
-- GrugFarHelpHeader xxx links to ModeMsg
-- GrugFarResultsAddIndicator xxx cleared
-- GrugFarResultsRemoveIndicator xxx cleared
-- GrugFarResultsChangeIndicator xxx cleared
-- GrugFarResultsLineNr xxx links to LineNr
-- GrugFarResultsNumbersSeparator xxx links to GrugFarResultsLineNr
-- GrugFarResultsColumnNr xxx links to GrugFarResultsLineNr
-- GrugFarResultsCursorLineNo xxx links to CursorLineNr
-- GrugFarResultsDiffSeparatorIndicator xxx links to Normal
-- GrugFarResultsPath xxx links to Underlined
-- GrugFarResultsMatchRemoved xxx links to DiffDelete
-- GrugFarResultsCmdHeader xxx links to Underlined
-- GrugFarResultsMatchAdded xxx links to DiffAdd
-- GrugFarResultsNumberLabel xxx links to Identifier
-- GrugFarResultsMatch xxx links to DiffText
-- GrugFarHelpWinActionKey xxx links to Identifier
-- GrugFarResultsActionMessage xxx links to ModeMsg
-- GrugFarHelpWinActionDescription xxx links to NormalFloat
-- GrugFarResultsStats xxx links to Comment
-- GrugFarResultsHeader xxx links to Comment
-- GrugFarInputPlaceholder xxx links to Comment
-- GrugFarInputLabel xxx links to Title
-- IblIndent      xxx guifg=#282830
-- IblWhitespace  xxx guifg=#282830
-- IblScope       xxx guifg=#acacac
-- @ibl           xxx cleared
-- @ibl.indent.char.1 xxx cterm=nocombine gui=nocombine guifg=#878787 guibg=#2b2e2f
-- @ibl.whitespace.char.1 xxx cterm=nocombine gui=nocombine guifg=#282830
-- @ibl.scope.char.1 xxx cterm=nocombine gui=nocombine guifg=#9da380
-- @ibl.scope.underline.1 xxx cterm=underline gui=underline guisp=#9da380
-- lualine_transparent xxx gui=nocombine guifg=#c7c6c6 guibg=#2b2e2f
-- lualine_b_normal xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_a_normal xxx gui=bold,nocombine guifg=#000000 guibg=#87aab5
-- lualine_c_normal xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_b_visual xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_a_visual xxx gui=bold,nocombine guifg=#000000 guibg=#c2ac7b
-- lualine_c_visual xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_b_replace xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_a_replace xxx gui=bold,nocombine guifg=#000000 guibg=#bc9a9c
-- lualine_c_replace xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_b_inactive xxx gui=nocombine guifg=#acacac guibg=#34383d
-- lualine_a_inactive xxx gui=bold,nocombine guifg=#acacac guibg=#34383d
-- lualine_c_inactive xxx gui=nocombine guifg=#acacac guibg=#34383d
-- lualine_b_insert xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_a_insert xxx gui=bold,nocombine guifg=#000000 guibg=#9da380
-- lualine_c_insert xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_b_command xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_a_command xxx gui=bold,nocombine guifg=#000000 guibg=#bc9a9c
-- lualine_c_command xxx gui=nocombine guifg=#c8c4c4 guibg=#34383d
-- lualine_b_branch_normal xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_branch_insert xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_branch_visual xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_branch_replace xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_branch_command xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_branch_terminal xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_branch_inactive xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_diff_added_normal xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_added_insert xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_added_visual xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_added_replace xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_added_command xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_added_terminal xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_added_inactive xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_b_diff_modified_normal xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_modified_insert xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_modified_visual xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_modified_replace xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_modified_command xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_modified_terminal xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_modified_inactive xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_b_diff_removed_normal xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diff_removed_insert xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diff_removed_visual xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diff_removed_replace xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diff_removed_command xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diff_removed_terminal xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diff_removed_inactive xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_normal xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_insert xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_visual xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_replace xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_command xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_terminal xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_error_inactive xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_b_diagnostics_warn_normal xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_warn_insert xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_warn_visual xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_warn_replace xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_warn_command xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_warn_terminal xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_warn_inactive xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_b_diagnostics_info_normal xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_info_insert xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_info_visual xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_info_replace xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_info_command xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_info_terminal xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_info_inactive xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_normal xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_insert xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_visual xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_replace xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_command xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_terminal xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_diagnostics_hint_inactive xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_a_diff_added_normal xxx gui=nocombine guifg=#8faf77 guibg=#87aab5
-- lualine_a_diff_added_insert xxx gui=nocombine guifg=#8faf77 guibg=#9da380
-- lualine_a_diff_added_visual xxx gui=nocombine guifg=#8faf77 guibg=#c2ac7b
-- lualine_a_diff_added_replace xxx gui=nocombine guifg=#8faf77 guibg=#bc9a9c
-- lualine_a_diff_added_command xxx gui=nocombine guifg=#8faf77 guibg=#bc9a9c
-- lualine_a_diff_added_terminal xxx gui=nocombine guifg=#8faf77 guibg=#87aab5
-- lualine_a_diff_added_inactive xxx gui=nocombine guifg=#8faf77 guibg=#34383d
-- lualine_a_diff_modified_normal xxx gui=nocombine guifg=#e6be8c guibg=#87aab5
-- lualine_a_diff_modified_insert xxx gui=nocombine guifg=#e6be8c guibg=#9da380
-- lualine_a_diff_modified_visual xxx gui=nocombine guifg=#e6be8c guibg=#c2ac7b
-- lualine_a_diff_modified_replace xxx gui=nocombine guifg=#e6be8c guibg=#bc9a9c
-- lualine_a_diff_modified_command xxx gui=nocombine guifg=#e6be8c guibg=#bc9a9c
-- lualine_a_diff_modified_terminal xxx gui=nocombine guifg=#e6be8c guibg=#87aab5
-- lualine_a_diff_modified_inactive xxx gui=nocombine guifg=#e6be8c guibg=#34383d
-- lualine_a_diff_removed_normal xxx gui=nocombine guifg=#dc9e92 guibg=#87aab5
-- lualine_a_diff_removed_insert xxx gui=nocombine guifg=#dc9e92 guibg=#9da380
-- lualine_a_diff_removed_visual xxx gui=nocombine guifg=#dc9e92 guibg=#c2ac7b
-- lualine_a_diff_removed_replace xxx gui=nocombine guifg=#dc9e92 guibg=#bc9a9c
-- lualine_a_diff_removed_command xxx gui=nocombine guifg=#dc9e92 guibg=#bc9a9c
-- lualine_a_diff_removed_terminal xxx gui=nocombine guifg=#dc9e92 guibg=#87aab5
-- lualine_a_diff_removed_inactive xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_a_diagnostics_error_normal xxx gui=nocombine guifg=#dc9e92 guibg=#87aab5
-- lualine_a_diagnostics_error_insert xxx gui=nocombine guifg=#dc9e92 guibg=#9da380
-- lualine_a_diagnostics_error_visual xxx gui=nocombine guifg=#dc9e92 guibg=#c2ac7b
-- lualine_a_diagnostics_error_replace xxx gui=nocombine guifg=#dc9e92 guibg=#bc9a9c
-- lualine_a_diagnostics_error_command xxx gui=nocombine guifg=#dc9e92 guibg=#bc9a9c
-- lualine_a_diagnostics_error_terminal xxx gui=nocombine guifg=#dc9e92 guibg=#87aab5
-- lualine_a_diagnostics_error_inactive xxx gui=nocombine guifg=#dc9e92 guibg=#34383d
-- lualine_a_diagnostics_warn_normal xxx gui=nocombine guifg=#c2ac7b guibg=#87aab5
-- lualine_a_diagnostics_warn_insert xxx gui=nocombine guifg=#c2ac7b guibg=#9da380
-- lualine_a_diagnostics_warn_visual xxx gui=nocombine guifg=#c2ac7b guibg=#c2ac7b
-- lualine_a_diagnostics_warn_replace xxx gui=nocombine guifg=#c2ac7b guibg=#bc9a9c
-- lualine_a_diagnostics_warn_command xxx gui=nocombine guifg=#c2ac7b guibg=#bc9a9c
-- lualine_a_diagnostics_warn_terminal xxx gui=nocombine guifg=#c2ac7b guibg=#87aab5
-- lualine_a_diagnostics_warn_inactive xxx gui=nocombine guifg=#c2ac7b guibg=#34383d
-- lualine_a_diagnostics_info_normal xxx gui=nocombine guifg=#a6a4a4 guibg=#87aab5
-- lualine_a_diagnostics_info_insert xxx gui=nocombine guifg=#a6a4a4 guibg=#9da380
-- lualine_a_diagnostics_info_visual xxx gui=nocombine guifg=#a6a4a4 guibg=#c2ac7b
-- lualine_a_diagnostics_info_replace xxx gui=nocombine guifg=#a6a4a4 guibg=#bc9a9c
-- lualine_a_diagnostics_info_command xxx gui=nocombine guifg=#a6a4a4 guibg=#bc9a9c
-- lualine_a_diagnostics_info_terminal xxx gui=nocombine guifg=#a6a4a4 guibg=#87aab5
-- lualine_a_diagnostics_info_inactive xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_a_diagnostics_hint_normal xxx gui=nocombine guifg=#a6a4a4 guibg=#87aab5
-- lualine_a_diagnostics_hint_insert xxx gui=nocombine guifg=#a6a4a4 guibg=#9da380
-- lualine_a_diagnostics_hint_visual xxx gui=nocombine guifg=#a6a4a4 guibg=#c2ac7b
-- lualine_a_diagnostics_hint_replace xxx gui=nocombine guifg=#a6a4a4 guibg=#bc9a9c
-- lualine_a_diagnostics_hint_command xxx gui=nocombine guifg=#a6a4a4 guibg=#bc9a9c
-- lualine_a_diagnostics_hint_terminal xxx gui=nocombine guifg=#a6a4a4 guibg=#87aab5
-- lualine_a_diagnostics_hint_inactive xxx gui=nocombine guifg=#a6a4a4 guibg=#34383d
-- lualine_b_15_normal xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_15_insert xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_15_visual xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_15_replace xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_15_command xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_15_terminal xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- lualine_b_15_inactive xxx gui=nocombine guifg=#dacaa5 guibg=#34383d
-- GitSignsAdd    xxx guifg=#cad2a5
-- GitGutterAdd   xxx cleared
-- SignifySignAdd xxx cleared
-- DiffAddedGutter xxx cleared
-- GitSignsChange xxx links to Keyword
-- GitGutterChange xxx cleared
-- SignifySignChange xxx cleared
-- DiffModifiedGutter xxx cleared
-- GitSignsDelete xxx links to Removed
-- GitGutterDelete xxx cleared
-- SignifySignDelete xxx cleared
-- DiffRemovedGutter xxx cleared
-- GitSignsChangedelete xxx links to GitSignsChange
-- GitSignsTopdelete xxx links to GitSignsDelete
-- GitSignsUntracked xxx links to GitSignsAdd
-- GitSignsAddNr  xxx links to GitSignsAdd
-- GitGutterAddLineNr xxx cleared
-- GitSignsChangeNr xxx links to GitSignsChange
-- GitGutterChangeLineNr xxx cleared
-- GitSignsDeleteNr xxx links to GitSignsDelete
-- GitGutterDeleteLineNr xxx cleared
-- GitSignsChangedeleteNr xxx links to GitSignsChangeNr
-- GitSignsTopdeleteNr xxx links to GitSignsDeleteNr
-- GitSignsUntrackedNr xxx links to GitSignsAddNr
-- GitSignsAddLn  xxx links to DiffAdd
-- GitGutterAddLine xxx cleared
-- SignifyLineAdd xxx cleared
-- GitSignsChangeLn xxx links to DiffChange
-- GitGutterChangeLine xxx cleared
-- SignifyLineChange xxx cleared
-- GitSignsChangedeleteLn xxx links to GitSignsChangeLn
-- GitSignsTopdeleteLn xxx links to GitSignsDeleteLn
-- GitSignsDeleteLn xxx cleared
-- GitSignsUntrackedLn xxx links to GitSignsAddLn
-- GitSignsAddCul xxx links to GitSignsAdd
-- GitSignsChangeCul xxx links to GitSignsChange
-- GitSignsDeleteCul xxx links to GitSignsDelete
-- GitSignsChangedeleteCul xxx links to GitSignsChangeCul
-- GitSignsTopdeleteCul xxx links to GitSignsDeleteCul
-- GitSignsUntrackedCul xxx links to GitSignsAddCul
-- GitSignsStagedAdd xxx guifg=#47573b
-- GitSignsStagedChange xxx guifg=#735f46
-- GitSignsStagedDelete xxx guifg=#6e4f49
-- GitSignsStagedChangedelete xxx guifg=#735f46
-- GitSignsStagedTopdelete xxx guifg=#6e4f49
-- GitSignsStagedUntracked xxx guifg=#47573b
-- GitSignsStagedAddNr xxx guifg=#47573b
-- GitSignsStagedChangeNr xxx guifg=#735f46
-- GitSignsStagedDeleteNr xxx guifg=#6e4f49
-- GitSignsStagedChangedeleteNr xxx guifg=#735f46
-- GitSignsStagedTopdeleteNr xxx guifg=#6e4f49
-- GitSignsStagedUntrackedNr xxx guifg=#47573b
-- GitSignsStagedAddLn xxx guibg=#3f483d
-- GitSignsStagedChangeLn xxx guibg=#504b42
-- GitSignsStagedChangedeleteLn xxx guibg=#504b42
-- GitSignsStagedTopdeleteLn xxx cleared
-- GitSignsStagedUntrackedLn xxx guibg=#3f483d
-- GitSignsStagedAddCul xxx guifg=#47573b
-- GitSignsStagedChangeCul xxx guifg=#735f46
-- GitSignsStagedDeleteCul xxx guifg=#6e4f49
-- GitSignsStagedChangedeleteCul xxx guifg=#735f46
-- GitSignsStagedTopdeleteCul xxx guifg=#6e4f49
-- GitSignsStagedUntrackedCul xxx guifg=#47573b
-- GitSignsAddPreview xxx links to DiffAdd
-- GitSignsDeletePreview xxx links to DiffDelete
-- GitGutterDeleteLine xxx cleared
-- SignifyLineDelete xxx cleared
-- GitSignsCurrentLineBlame xxx links to NonText
-- GitSignsAddInline xxx links to TermCursor
-- GitSignsDeleteInline xxx links to TermCursor
-- GitSignsChangeInline xxx links to TermCursor
-- GitSignsAddLnInline xxx links to GitSignsAddInline
-- GitSignsChangeLnInline xxx links to GitSignsChangeInline
-- GitSignsDeleteLnInline xxx links to GitSignsDeleteInline
-- GitSignsDeleteVirtLn xxx links to DiffDelete
-- GitSignsDeleteVirtLnInLine xxx links to GitSignsDeleteLnInline
-- GitSignsVirtLnum xxx links to GitSignsDeleteVirtLn
-- TreesitterContext xxx guibg=#282830
-- TreesitterContextLineNumber xxx guifg=#acacac guibg=#282830
-- NONE           xxx cleared
-- TreesitterContextBottom xxx links to NONE
-- TreesitterContextLineNumberBottom xxx links to TreesitterContextBottom
-- TreesitterContextSeparator xxx links to FloatBorder
-- SagaBorder     xxx links to FloatBorder
-- RenameBorder   xxx links to SagaBorder
-- HoverBorder    xxx links to SagaBorder
-- SagaNormal     xxx links to NormalFloat
-- HoverNormal    xxx links to SagaNormal
-- CodeActionCursorLine xxx links to CursorLine
-- CodeActionNumber xxx links to DiffAdd
-- SagaTitle      xxx links to Title
-- SagaDetail     xxx links to Comment
-- SagaSearch     xxx links to Search
-- SagaSelect     xxx links to String
-- CodeActionText xxx links to @variable
-- SagaSpinnerTitle xxx links to Statement
-- ActionPreviewTitle xxx links to Title
-- ActionPreviewBorder xxx links to SagaBorder
-- ActionPreviewNormal xxx links to SagaNormal
-- SagaSep        xxx links to Comment
-- SagaCount      xxx cleared
-- SagaSpinner    xxx links to Statement
-- SagaText       xxx links to Comment
-- SagaFolderName xxx links to Comment
-- SagaFileName   xxx links to Comment
-- SagaFolder     xxx links to Title
-- SagaWinbarFolder xxx links to SagaFolder
-- SagaFinderFname xxx links to Function
-- SagaWinbarFolderName xxx links to SagaFolderName
-- SagaWinbarFileName xxx links to SagaFileName
-- SagaWinbarSep  xxx links to Operator
-- SagaImpIcon    xxx links to PreProc
-- TerminalNormal xxx links to SagaNormal
-- SagaVirtLine   xxx cleared
-- TerminalBorder xxx links to SagaBorder
-- SagaBeacon     xxx cleared
-- SagaLightBulb  xxx links to DiagnosticSignHint
-- SagaToggle     xxx links to Comment
-- DiagnosticShowBorder xxx links to @property
-- SagaInCurrent  xxx links to Keyword
-- DiagnosticShowNormal xxx links to SagaNormal
-- DiagnosticText xxx cleared
-- DiagnosticNormal xxx links to SagaNormal
-- DiagnosticBorder xxx links to SagaBorder
-- RenameMatch    xxx links to Search
-- RenameNormal   xxx links to Statement
-- SagaFile       xxx links to Tag
-- SagaModule     xxx links to Exception
-- SagaNamespace  xxx links to Include
-- SagaPackage    xxx links to Label
-- SagaClass      xxx links to Include
-- SagaMethod     xxx links to Function
-- SagaProperty   xxx links to @property
-- @field         xxx cleared
-- SagaField      xxx links to @field
-- SagaConstructor xxx links to @constructor
-- SagaEnum       xxx links to @number
-- SagaInterface  xxx links to Type
-- SagaFunction   xxx links to Function
-- SagaVariable   xxx links to @variable
-- SagaConstant   xxx links to Constant
-- SagaString     xxx links to String
-- SagaNumber     xxx links to Number
-- SagaBoolean    xxx links to Boolean
-- SagaArray      xxx links to Type
-- SagaObject     xxx links to Type
-- SagaKey        xxx links to Constant
-- SagaNull       xxx links to Constant
-- SagaEnumMember xxx links to Number
-- SagaStruct     xxx links to Type
-- SagaEvent      xxx links to Constant
-- SagaOperator   xxx links to Operator
-- SagaTypeParameter xxx links to Type
-- SagaTypeAlias  xxx links to Type
-- @parameter     xxx cleared
-- SagaParameter  xxx links to @parameter
-- SagaUnit       xxx links to Number
-- SagaStaticMethod xxx links to Function
-- SagaValue      xxx links to @variable
-- SagaMacro      xxx links to Macro
-- SagaSnippet    xxx links to @variable
-- DiagnosticERRORReverse xxx cleared
-- DiagnosticWARNReverse xxx cleared
-- DiagnosticINFOReverse xxx cleared
-- DiagnosticHINTReverse xxx cleared
-- SagaButton     xxx cleared
-- SagaActionTitle xxx cleared
-- FzfLuaNormal   xxx links to Normal
-- FzfLuaBorder   xxx guifg=#878787 guibg=#2b2e2f
-- FzfLuaTitle    xxx links to FzfLuaNormal
-- FzfLuaTitleFlags xxx links to CursorLine
-- FzfLuaBackdrop xxx cleared
-- FzfLuaHelpNormal xxx links to FzfLuaNormal
-- FzfLuaHelpBorder xxx links to FzfLuaBorder
-- FzfLuaPreviewNormal xxx links to FzfLuaNormal
-- FzfLuaPreviewBorder xxx links to FzfLuaBorder
-- FzfLuaPreviewTitle xxx links to FzfLuaTitle
-- FzfLuaCursor   xxx links to Cursor
-- FzfLuaCursorLine xxx links to CursorLine
-- FzfLuaCursorLineNr xxx links to CursorLineNr
-- FzfLuaSearch   xxx links to IncSearch
-- FzfLuaScrollBorderEmpty xxx links to FzfLuaBorder
-- FzfLuaScrollBorderFull xxx links to FzfLuaBorder
-- FzfLuaScrollFloatEmpty xxx links to PmenuSbar
-- FzfLuaScrollFloatFull xxx links to PmenuThumb
-- FzfLuaDirIcon  xxx links to Directory
-- FzfLuaDirPart  xxx links to Comment
-- @none          xxx cleared
-- FzfLuaFilePart xxx links to @none
-- FzfLuaHeaderBind xxx guifg=#c4aaa9
-- FzfLuaHeaderText xxx links to Error
-- FzfLuaPathColNr xxx guifg=#b9a3ba
-- FzfLuaPathLineNr xxx links to String
-- FzfLuaLivePrompt xxx guifg=#c4aaa9
-- FzfLuaLiveSym  xxx links to Error
-- FzfLuaBufId    xxx links to TabLine
-- FzfLuaBufName  xxx links to Directory
-- FzfLuaBufLineNr xxx links to LineNr
-- FzfLuaBufNr    xxx guifg=#9da380
-- FzfLuaBufFlagCur xxx links to Error
-- FzfLuaBufFlagAlt xxx guifg=#8cadc6
-- FzfLuaTabTitle xxx guifg=#a1b3b9
-- FzfLuaTabMarker xxx guifg=#c4aaa9
-- FzfLuaCmdEx    xxx links to Statement
-- FzfLuaCmdBuf   xxx links to Added
-- FzfLuaCmdGlobal xxx links to Directory
-- FzfLuaFzfNormal xxx links to FzfLuaNormal
-- FzfLuaFzfCursorLine xxx links to FzfLuaCursorLine
-- FzfLuaFzfMatch xxx links to Special
-- FzfLuaFzfBorder xxx links to FzfLuaBorder
-- FzfLuaFzfScrollbar xxx links to FzfLuaFzfBorder
-- FzfLuaFzfSeparator xxx links to FzfLuaFzfBorder
-- FzfLuaFzfGutter xxx links to FzfLuaNormal
-- FzfLuaFzfHeader xxx links to FzfLuaTitle
-- FzfLuaFzfInfo  xxx links to NonText
-- FzfLuaFzfPointer xxx links to Special
-- FzfLuaFzfMarker xxx links to FzfLuaFzfPointer
-- FzfLuaFzfSpinner xxx links to FzfLuaFzfPointer
-- FzfLuaFzfPrompt xxx links to Special
-- FzfLuaFzfQuery xxx links to FzfLuaNormal
-- fzf1           xxx cleared
-- fzf2           xxx cleared
-- fzf3           xxx cleared
-- @lsp.type.selfParameter xxx guifg=#a3b8b6
-- @lsp.type.generic xxx guifg=#a1b3b9
-- @lsp.type.builtinType xxx guifg=#a3b8b6
-- @lsp.type.builtinConstant xxx guifg=#dacaa5
-- htmlSpecialTagName xxx guifg=#a3b8b6
-- htmlArg        xxx guifg=#c4aaa9
-- htmlTagName    xxx guifg=#a3b8b6
-- htmlEndTag     xxx guifg=#c7c6c6
-- htmlTag        xxx guifg=#c7c6c6
-- @lsp.typemod.variable.definition xxx guifg=#c7c7d4
-- @lsp.typemod.variable.defaultLibrary xxx guifg=#dacaa5
-- @lsp.typemod.function xxx guifg=#b9a3ba
-- @lsp.typemod.function.definition xxx guifg=#c0a3a5
-- @lsp.typemod.function.defaultLibrary xxx guifg=#c0a3a5
-- @lsp.typemod.function.builtin xxx guifg=#c0a3a5
-- @type.declaration xxx guifg=#c4aaa9
-- @tag.delimiter xxx guifg=#c7c6c6
-- @string.special.symbol xxx guifg=#c4aaa9
-- @markup.quote.markdown xxx guifg=#acacac
-- @markup.math   xxx guifg=#9da380
-- @markup.list   xxx guifg=#c0a3a5
-- @keyword.return xxx guifg=#8cadc6
-- @keyword.operator xxx guifg=#8cadc6
-- @keyword.conditional xxx guifg=#8cadc6
-- @function.macro xxx guifg=#c4aaa9
-- @text          xxx cleared
-- @text.diff.delete xxx guibg=#4e4443
-- @text.diff.add xxx guibg=#3f483d
-- @constructor.lua xxx guifg=#a1b3b9
-- LspCxxHlSkippedRegionBeginEnd xxx guifg=#96a3b2
-- LspCxxHlSkippedRegion xxx guifg=#acacac
-- LspCxxHlGroupNamespace xxx guifg=#c0a3a5
-- LspCxxHlGroupMemberVariable xxx guifg=#a1b3b9
-- LspCxxHlGroupEnumConstant xxx guifg=#a1b3b9
-- BlinkCmpLabelMatch xxx links to String
-- BlinkCmpLabel  xxx guifg=#c7c6c6
-- BlinkCmpLabelDeprecated xxx guifg=#dc9e92
-- MiniStatuslineInactive xxx guifg=#acacac guibg=#2b2e2f
-- MiniStatuslineFileinfo xxx guifg=#c7c6c6 guibg=#1c1c24
-- MiniStatuslineFilename xxx guifg=#acacac guibg=#2b2e2f
-- MiniStatuslineDevinfo xxx guifg=#c7c6c6 guibg=#1c1c24
-- MiniStatuslineModeOther xxx gui=bold guifg=#2b2e2f guibg=#9da380
-- MiniStatuslineModeCommand xxx gui=bold guifg=#2b2e2f guibg=#9da380
-- MiniStatuslineModeReplace xxx gui=bold guifg=#2b2e2f guibg=#9da380
-- MiniStatuslineModeVisual xxx gui=bold guifg=#2b2e2f guibg=#a3b8b6
-- MiniStatuslineModeInsert xxx gui=bold guifg=#2b2e2f guibg=#e6be8c
-- MiniStatuslineModeNormal xxx gui=bold guifg=#2b2e2f guibg=#96a3b2
-- MiniDiffSignDelete xxx guifg=#dc9e92
-- MiniDiffSignChange xxx guifg=#e6be8c
-- MiniDiffSignAdd xxx guifg=#8faf77
-- MiniDiffOverContext xxx guibg=#282830
-- Terminal       xxx guifg=#c7c6c6 guibg=#2b2e2f
-- ModesInsertCursorLineSign xxx guibg=#282830
-- ModesInsertCursorLineFold xxx guibg=#282830
-- ModesInsertCursorLineNr xxx guibg=#282830
-- ModesInsertCursorLine xxx guibg=#282830
-- ModesInsert    xxx guibg=#c4aaa9
-- ModesVisual    xxx guibg=#dacaa5
-- ModesReplace   xxx guibg=#8faf77
-- ModesFormat    xxx guibg=#c0a3a5
-- ModesDelete    xxx guibg=#dc9e92
-- TelescopeResultsNormal xxx guifg=#c7c6c6
-- ExtraWhitespace xxx guifg=#c7c6c6 guibg=#dc9e92
-- @function.method.call xxx links to Function
-- @tag.attribute xxx cterm=bold gui=bold guifg=Grey70
-- ToolbarButton  xxx guifg=#2b2e2f guibg=#51575d
-- @keyword.exception xxx guifg=#8cadc6
-- @markup.link.uri xxx gui=underline guifg=#9da380
-- @markup.raw    xxx guifg=#c4aaa9
-- NeotestFailed  xxx guifg=#dc9e92
-- CmpItemAbbr    xxx guifg=#c7c6c6
-- CmpItemAbbrDeprecated xxx guifg=#dc9e92
-- RainbowDelimiterYellow xxx guifg=#c2ac7b
-- RainbowDelimiterGreen xxx guifg=#8faf77
-- RainbowDelimiterBlue xxx guifg=#a6a4a4
-- RainbowDelimiterViolet xxx guifg=#b9a3ba
-- RainbowDelimiterCyan xxx guifg=#8cadc6
-- SnacksIndentChunk xxx guifg=#acacac
-- SnacksIndent   xxx guifg=#acacac
-- SnacksIndentScope xxx guifg=#acacac
-- DiffFile       xxx guifg=#8cadc6
-- ModesCopy      xxx guibg=#8cadc6
-- DiffIndexLine  xxx guifg=#acacac
-- NeotestSkipped xxx guifg=#c2ac7b
-- NeotestFocused xxx gui=bold guifg=#e6be8c
-- netrwClassify  xxx guifg=#a6a4a4
-- netrwTreeBar   xxx guifg=#acacac
-- CmpItemKind    xxx guifg=#acacac
-- debugPC        xxx guifg=#2b2e2f guibg=#c7c6c6
-- NeotestIndent  xxx guifg=#acacac
-- BlinkCmpSignatureHelpBorder xxx guifg=#878787
-- NeotestNamespace xxx guifg=#b9a3ba
-- NeotestAdapterName xxx gui=bold guifg=#a6a4a4
-- BlinkCmpMenuBorder xxx guifg=#878787
-- BlinkCmpMenu   xxx guifg=#c7c6c6
-- NeotestTarget  xxx guifg=#a6a4a4
-- NeotestWatching xxx guifg=#c2ac7b
-- NeotestMarked  xxx guifg=#e6be8c
-- BlinkCmpGhostText xxx guifg=#acacac
-- NeotestPassed  xxx guifg=#8faf77
-- BlinkCmpDocBorder xxx guifg=#878787
-- NeotestDir     xxx guifg=#acacac
-- NeotestUnknown xxx guifg=#c7c6c6
-- NeotestTest    xxx guifg=#acacac
-- RainbowDelimiterOrange xxx guifg=#c0a3a5
-- RainbowDelimiterRed xxx guifg=#dc9e92
-- @variable.member xxx links to @variable
-- @keyword.import xxx links to @keyword
-- @function.call xxx links to Function
-- TelescopeSelectionCaret xxx links to Function
-- TelescopeSelection xxx links to Visual
-- TelescopeMatching xxx links to CursorLineNr
-- NeoTreeSymbolicLinkTarget xxx guifg=#a6a4a4
-- NeoTreeIndentMarker xxx guifg=#acacac
-- NeoTreeGitUntracked xxx guifg=#dc9e92
-- NeoTreeGitConflict xxx guifg=#dc9e92
-- NeoTreeGitModified xxx guifg=#e6be8c
-- NeoTreeGitDeleted xxx guifg=#dc9e92
-- NeoTreeGitAdded xxx guifg=#8faf77
-- NeoTreeRootName xxx guifg=#a6a4a4
-- NeoTreeEndOfBuffer xxx guifg=#acacac guibg=#2b2e2f
-- NeoTreeWinSeparator xxx guifg=#acacac guibg=#acacac
-- NeoTreeVertSplit xxx guifg=#acacac guibg=#acacac
-- NeoTreeNormalNC xxx guifg=#c7c6c6 guibg=#2b2e2f
-- NeoTreeNormal  xxx guifg=#c7c6c6 guibg=#2b2e2f
-- CmpGhostText   xxx guifg=#acacac
-- ToolbarLine    xxx guifg=#c7c6c6
-- SnacksInputIcon xxx guifg=#c4aaa9
-- SnacksInputTitle xxx guifg=#c4aaa9
-- SnacksInputPrompt xxx guifg=#acacac
-- SnacksInputBorder xxx guifg=#878787
-- CmpItemAbbrMatch xxx links to String
-- debugBreakpoint xxx guifg=#2b2e2f guibg=#96a3b2
-- SnacksPickerGitStatusStaged xxx guifg=#8faf77
-- SnacksPickerGitStatusModified xxx guifg=#e6be8c
-- SnacksPickerGitStatusAdded xxx guifg=#8faf77
-- SnacksPickerGitStatusUntracked xxx guifg=#dc9e92
-- SnacksPickerPreviewCursorLine xxx guifg=#c4aaa9 guibg=#282830
-- SnacksPickerInputCursorLine xxx guifg=#c4aaa9 guibg=#282830
-- SnacksPickerListCursorLine xxx guifg=#c4aaa9 guibg=#282830
-- SnacksPickerCursorLine xxx guifg=#c4aaa9 guibg=#282830
-- SnacksPickerPrewviewBorder xxx guifg=#878787
-- SnacksPickerInputBorder xxx guifg=#878787
-- SnacksPickerListBorder xxx guifg=#878787
-- SnacksPickerBoxBorder xxx guifg=#878787
-- SnacksPickerBorder xxx guifg=#878787
-- TelescopeBorder xxx guifg=#878787
-- SnacksPickerPrompt xxx guifg=#c4aaa9
-- TelescopePromptPrefix xxx guifg=#c4aaa9
-- SnacksPickerMatch xxx gui=bold guifg=#e6be8c
-- DashboardFooter xxx gui=italic guifg=#e6be8c
-- DashboardCenter xxx guifg=#c4aaa9
-- DashboardHeader xxx guifg=#c4aaa9
-- DashboardShortCut xxx guifg=#b9a3ba
-- CmpItemAbbrMatchFuzzy xxx gui=bold guifg=#e6be8c
-- CmpItemMenu    xxx guifg=#c7c6c6
-- NeotestFile    xxx guifg=#c4aaa9
-- NeotestRunning xxx guifg=#a6a4a4
-- SnacksPickerBoxCursorLine xxx guifg=#c4aaa9 guibg=#282830
-- lualine_b_terminal xxx cleared
-- lualine_a_terminal xxx cleared
-- @punctuation.bracket xxx guifg=#a4bac1
-- CmpItemKindKeyword xxx links to Keyword
-- CmpItemKindClass xxx links to Type
-- CmpItemKindMethod xxx links to Function
-- CmpItemKindField xxx links to Constant
-- CmpItemKindProperty xxx links to Number
-- BlinkCmpKindClass xxx links to Type
-- BlinkCmpKindEnum xxx links to Type
-- BlinkCmpKindInterface xxx links to Type
-- BlinkCmpKindStruct xxx links to Type
-- Variable       xxx cleared
-- BlinkCmpKindField xxx links to Variable
-- BlinkCmpKindKeyword xxx links to Keyword
-- BlinkCmpKindMethod xxx links to Function
-- BlinkCmpKindFunction xxx links to Function
-- BlinkCmpKindEnumMember xxx links to Constant
-- BlinkCmpKindConstant xxx links to Constant
-- BlinkCmpKindText xxx links to Comment
-- BlinkCmpKindProperty xxx links to Variable
-- BlinkCmpKindUnit xxx links to Variable
-- BlinkCmpKindFile xxx links to Variable
-- BlinkCmpKindValue xxx links to Variable
-- BlinkCmpKindColor xxx links to Variable
-- BlinkCmpKindEvent xxx links to Variable
-- BlinkCmpKindModule xxx links to Variable
-- BlinkCmpKindFolder xxx links to Variable
-- BlinkCmpKindSnippet xxx links to Variable
-- BlinkCmpKindVariable xxx links to Variable
-- BlinkCmpKindOperator xxx links to Variable
-- BlinkCmpKindReference xxx links to Variable
-- BlinkCmpKindConstructor xxx links to Variable
-- BlinkCmpKindTypeParameter xxx links to Variable
-- DiffAdded      xxx links to DiffAdd
-- @spell         xxx cleared
-- @spell.gitcommit xxx links to String
-- @markup.heading.gitcommit xxx links to Function
-- @markup.link.gitcommit xxx links to Number
-- @string.special.path.gitcommit xxx links to Constant
-- fugitiveSymbolicRef xxx links to Number
-- TelescopeMatchingAlternate xxx links to Number
-- DevIconPhp     xxx links to Function
-- DevIconH       xxx links to Keyword
-- DevIconCpp     xxx links to Function
-- FlashLabel     xxx cterm=bold gui=bold guifg=#ffffff
-- DevIconDefault xxx ctermfg=66 guifg=#6d8086
-- DevIconExe     xxx ctermfg=124 guifg=#9f0500
-- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
-- DevIconBicep   xxx ctermfg=74 guifg=#519aba
-- DevIconAdaFile xxx ctermfg=111 guifg=#599eff
-- DevIconVoid    xxx ctermfg=23 guifg=#295340
-- DevIconTerminal xxx ctermfg=34 guifg=#31b53e
-- DevIconCheckhealth xxx ctermfg=75 guifg=#75b4fb
-- DevIconPyLintConfig xxx ctermfg=66 guifg=#6d8086
-- DevIconZsh     xxx ctermfg=113 guifg=#89e051
-- DevIconBin     xxx ctermfg=124 guifg=#9f0500
-- DevIconASM     xxx ctermfg=31 guifg=#0091bd
-- DevIconAsciinema xxx ctermfg=208 guifg=#fd971f
-- DevIconVue     xxx ctermfg=113 guifg=#8dc149
-- DevIconSvelte  xxx ctermfg=196 guifg=#ff3e00
-- DevIconDownload xxx ctermfg=43 guifg=#44cda8
-- DevIconCache   xxx ctermfg=231 guifg=#ffffff
-- DevIconLinux   xxx ctermfg=231 guifg=#fdfdfb
-- DevIconTsx     xxx ctermfg=26 guifg=#1354bf
-- DevIconAsc     xxx ctermfg=242 guifg=#576d7f
-- DevIconUbuntu  xxx ctermfg=196 guifg=#dd4814
-- DevIconLuau    xxx ctermfg=75 guifg=#00a2ff
-- DevIconJsonc   xxx ctermfg=185 guifg=#cbcb41
-- DevIconDockerfile xxx ctermfg=68 guifg=#458ee6
-- DevIconOpenGLShadingLanguage xxx ctermfg=67 guifg=#5586a6
-- DevIconAstro   xxx ctermfg=197 guifg=#e23f67
-- DevIconTmux    xxx ctermfg=34 guifg=#14ba19
-- DevIconNodeModules xxx ctermfg=197 guifg=#e8274b
-- DevIconLocalization xxx ctermfg=31 guifg=#2596be
-- DevIconGvimrc  xxx ctermfg=28 guifg=#019833
-- DevIconConfig  xxx ctermfg=66 guifg=#6d8086
-- DevIconBazelBuild xxx ctermfg=113 guifg=#89e051
-- DevIconGitLogo xxx ctermfg=196 guifg=#f14c28
-- DevIconLibreOfficeCalc xxx ctermfg=119 guifg=#78fc4e
-- DevIconLibreOfficeImpress xxx ctermfg=215 guifg=#fe9c45
-- DevIconGarudaLinux xxx ctermfg=33 guifg=#2974e1
-- DevIconXsession xxx ctermfg=196 guifg=#e54d18
-- DevIconFreeBSD xxx ctermfg=160 guifg=#c90f02
-- DevIconXInitrc xxx ctermfg=196 guifg=#e54d18
-- DevIconVimrc   xxx ctermfg=28 guifg=#019833
-- DevIconFedora  xxx ctermfg=17 guifg=#072a5e
-- DevIconLibreOfficeFormula xxx ctermfg=204 guifg=#ff5a96
-- DevIconEndeavour xxx ctermfg=91 guifg=#7b3db9
-- DevIconPrettierConfig xxx ctermfg=33 guifg=#4285f4
-- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
-- DevIconPrettierIgnore xxx ctermfg=33 guifg=#4285f4
-- DevIconImportConfiguration xxx ctermfg=255 guifg=#ececec
-- DevIconDeepin  xxx ctermfg=39 guifg=#2ca7f8
-- DevIconDebian  xxx ctermfg=88 guifg=#a80030
-- DevIconNfo     xxx ctermfg=230 guifg=#ffffcd
-- DevIconCrystalLinux xxx ctermfg=129 guifg=#a900ff
-- DevIconLess    xxx ctermfg=54 guifg=#563d7c
-- DevIconNPMrc   xxx ctermfg=197 guifg=#e8274b
-- DevIconBigLinux xxx ctermfg=38 guifg=#189fc8
-- DevIconArtix   xxx ctermfg=38 guifg=#41b4d7
-- DevIconElisp   xxx ctermfg=97 guifg=#8172be
-- DevIconArcoLinux xxx ctermfg=68 guifg=#6690eb
-- DevIconArchlabs xxx ctermfg=238 guifg=#503f42
-- DevIconArduino xxx ctermfg=73 guifg=#56b6c2
-- DevIconGitBlameIgnore xxx ctermfg=196 guifg=#f54d27
-- DevIconArchcraft xxx ctermfg=108 guifg=#86bba3
-- DevIconRmd     xxx ctermfg=74 guifg=#519aba
-- DevIconEnv     xxx ctermfg=227 guifg=#faf743
-- DevIconPatch   xxx ctermfg=239 guifg=#41535b
-- DevIconApple   xxx ctermfg=248 guifg=#a2aaad
-- DevIconAOSC    xxx ctermfg=124 guifg=#c00000
-- DevIconDsStore xxx ctermfg=239 guifg=#41535b
-- DevIconAlpine  xxx ctermfg=24 guifg=#0d597f
-- DevIconCodespell xxx ctermfg=41 guifg=#35da60
-- DevIconAlmalinux xxx ctermfg=203 guifg=#ff4649
-- DevIconBlueprint xxx ctermfg=68 guifg=#5796e2
-- DevIconGroovy  xxx ctermfg=24 guifg=#4a687c
-- DevIconGv      xxx ctermfg=24 guifg=#30638e
-- DevIconViteConfig xxx ctermfg=214 guifg=#ffa800
-- DevIconAwk     xxx ctermfg=240 guifg=#4d5a5e
-- DevIconGoSum   xxx ctermfg=38 guifg=#00add8
-- DevIconClojureJS xxx ctermfg=74 guifg=#519aba
-- DevIcon7z      xxx ctermfg=214 guifg=#eca517
-- DevIconHtm     xxx ctermfg=196 guifg=#e34c26
-- DevIconExs     xxx ctermfg=140 guifg=#a074c4
-- DevIconElm     xxx ctermfg=74 guifg=#519aba
-- DevIconLogos   xxx ctermfg=111 guifg=#599eff
-- DevIcon3DObjectFile xxx ctermfg=102 guifg=#888888
-- DevIconLXQt    xxx ctermfg=32 guifg=#0191d2
-- DevIconLrc     xxx ctermfg=214 guifg=#ffb713
-- DevIconLXDE    xxx ctermfg=248 guifg=#a4a4a4
-- DevIconNPMIgnore xxx ctermfg=197 guifg=#e8274b
-- DevIconGNOME   xxx ctermfg=231 guifg=#ffffff
-- DevIconCinnamon xxx ctermfg=166 guifg=#dc682e
-- DevIconEdn     xxx ctermfg=74 guifg=#519aba
-- DevIconBudgie  xxx ctermfg=240 guifg=#4e5361
-- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
-- DevIconCsh     xxx ctermfg=240 guifg=#4d5a5e
-- DevIconXml     xxx ctermfg=166 guifg=#e37933
-- DevIconXslt    xxx ctermfg=74 guifg=#33a9dc
-- DevIconSvg     xxx ctermfg=214 guifg=#ffb13b
-- DevIconHexadecimal xxx ctermfg=27 guifg=#2e63ff
-- DevIconM3u8    xxx ctermfg=211 guifg=#ed95ae
-- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
-- DevIconR       xxx ctermfg=25 guifg=#2266ba
-- DevIconTypst   xxx ctermfg=37 guifg=#0dbcc0
-- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
-- DevIconTypeScript xxx ctermfg=74 guifg=#519aba
-- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
-- DevIconApp     xxx ctermfg=124 guifg=#9f0500
-- DevIconXcLocalization xxx ctermfg=31 guifg=#2596be
-- DevIconHh      xxx ctermfg=140 guifg=#a074c4
-- DevIconHrl     xxx ctermfg=163 guifg=#b83998
-- DevIconElf     xxx ctermfg=124 guifg=#9f0500
-- DevIconCxx     xxx ctermfg=74 guifg=#519aba
-- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
-- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
-- DevIconIxx     xxx ctermfg=74 guifg=#519aba
-- DevIconMpp     xxx ctermfg=74 guifg=#519aba
-- DevIconCPlusPlusModule xxx ctermfg=204 guifg=#f34b7d
-- DevIconCppm    xxx ctermfg=74 guifg=#519aba
-- DevIconCxxm    xxx ctermfg=74 guifg=#519aba
-- DevIconsbt     xxx ctermfg=167 guifg=#cc3e44
-- DevIconWavPackCorrection xxx ctermfg=39 guifg=#00afff
-- DevIconPackageLockJson xxx ctermfg=52 guifg=#7a0d21
-- DevIconPNPMLock xxx ctermfg=214 guifg=#f9ad02
-- DevIconBunLockfile xxx ctermfg=253 guifg=#eadcd1
-- DevIconVRML    xxx ctermfg=102 guifg=#888888
-- DevIconRazorPage xxx ctermfg=56 guifg=#512bd4
-- DevIconWebOpenFontFormat xxx ctermfg=255 guifg=#ececec
-- DevIconCss     xxx ctermfg=91 guifg=#663399
-- DevIconcudah   xxx ctermfg=140 guifg=#a074c4
-- DevIconWindowsMediaVideo xxx ctermfg=208 guifg=#fd971f
-- DevIconTxt     xxx ctermfg=113 guifg=#89e051
-- DevIconClangConfig xxx ctermfg=66 guifg=#6d8086
-- DevIconSystemVerilog xxx ctermfg=28 guifg=#019833
-- DevIconWindowsMediaAudio xxx ctermfg=39 guifg=#00afff
-- DevIconJson5   xxx ctermfg=185 guifg=#cbcb41
-- DevIconBazelWorkspace xxx ctermfg=113 guifg=#89e051
-- DevIconTex     xxx ctermfg=22 guifg=#3d6117
-- DevIconWaveformAudioFile xxx ctermfg=39 guifg=#00afff
-- DevIconIni     xxx ctermfg=66 guifg=#6d8086
-- DevIconKotlinScript xxx ctermfg=99 guifg=#7f52ff
-- DevIconKotlin  xxx ctermfg=99 guifg=#7f52ff
-- DevIconVsix    xxx ctermfg=98 guifg=#854cc7
-- DevIconHs      xxx ctermfg=140 guifg=#a074c4
-- DevIconZigObjectNotation xxx ctermfg=172 guifg=#f69a1b
-- DevIconIso     xxx ctermfg=181 guifg=#d0bec8
-- DevIconStaticLibraryArchive xxx ctermfg=253 guifg=#dcddd6
-- DevIconBSPWM   xxx ctermfg=236 guifg=#2f2f2f
-- DevIconErl     xxx ctermfg=163 guifg=#b83998
-- DevIconLicense xxx ctermfg=185 guifg=#cbcb41
-- DevIconMaterial xxx ctermfg=163 guifg=#b83998
-- DevIconEx      xxx ctermfg=140 guifg=#a074c4
-- DevIconEex     xxx ctermfg=140 guifg=#a074c4
-- DevIconPNPMWorkspace xxx ctermfg=214 guifg=#f9ad02
-- DevIconTorrent xxx ctermfg=43 guifg=#44cda8
-- DevIconNuxtConfig xxx ctermfg=42 guifg=#00c58e
-- DevIconNushell xxx ctermfg=36 guifg=#3aa675
-- DevIconXul     xxx ctermfg=166 guifg=#e37933
-- DevIconSub     xxx ctermfg=214 guifg=#ffb713
-- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
-- DevIconNextConfigJs xxx ctermfg=231 guifg=#ffffff
-- DevIconSharedObject xxx ctermfg=253 guifg=#dcddd6
-- DevIconSh      xxx ctermfg=240 guifg=#4d5a5e
-- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
-- DevIconTgz     xxx ctermfg=214 guifg=#eca517
-- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
-- DevIconPyi     xxx ctermfg=214 guifg=#ffbc03
-- DevIconHypridle xxx ctermfg=37 guifg=#00aaae
-- DevIconHyprlock xxx ctermfg=37 guifg=#00aaae
-- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
-- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
-- DevIconCue     xxx ctermfg=211 guifg=#ed95ae
-- DevIconOggVorbis xxx ctermfg=24 guifg=#0075aa
-- DevIconTerraform xxx ctermfg=93 guifg=#5f43e9
-- DevIconBrewfile xxx ctermfg=52 guifg=#701516
-- DevIconTestTs  xxx ctermfg=74 guifg=#519aba
-- DevIconOggVideo xxx ctermfg=208 guifg=#fd971f
-- DevIconJavaScriptReactTest xxx ctermfg=45 guifg=#20c2e3
-- DevIconTails   xxx ctermfg=54 guifg=#56347c
-- DevIconTestJs  xxx ctermfg=185 guifg=#cbcb41
-- DevIconOggMultiplex xxx ctermfg=208 guifg=#fd971f
-- DevIconSuo     xxx ctermfg=98 guifg=#854cc7
-- DevIconNim     xxx ctermfg=220 guifg=#f3d400
-- DevIconSlackware xxx ctermfg=61 guifg=#475fa9
-- DevIconMl      xxx ctermfg=166 guifg=#e37933
-- DevIconPlaywrightConfig xxx ctermfg=34 guifg=#2fad33
-- DevIconLog     xxx ctermfg=253 guifg=#dddddd
-- DevIconTcl     xxx ctermfg=25 guifg=#1e5cb3
-- DevIconRlib    xxx ctermfg=216 guifg=#dea584
-- DevIconRedhat  xxx ctermfg=196 guifg=#ee0000
-- DevIconGitIgnore xxx ctermfg=196 guifg=#f54d27
-- DevIconQubesOS xxx ctermfg=33 guifg=#3774d8
-- DevIconSvgz    xxx ctermfg=214 guifg=#ffb13b
-- DevIconCrystal xxx ctermfg=251 guifg=#c8c8c8
-- DevIconPart    xxx ctermfg=43 guifg=#44cda8
-- DevIconReadme  xxx ctermfg=255 guifg=#ededed
-- DevIconEditorConfig xxx ctermfg=255 guifg=#fff2f2
-- DevIconpostmarketOS xxx ctermfg=28 guifg=#009900
-- DevIconCMake   xxx ctermfg=254 guifg=#dce3eb
-- DevIconopenSUSE xxx ctermfg=70 guifg=#6fb424
-- DevIconPulseCodeModulation xxx ctermfg=24 guifg=#0075aa
-- DevIconI18nConfig xxx ctermfg=104 guifg=#7986cb
-- DevIconParabolaGNULinuxLibre xxx ctermfg=103 guifg=#797dac
-- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
-- DevIconBazel   xxx ctermfg=113 guifg=#89e051
-- DevIconMonkeysAudio xxx ctermfg=39 guifg=#00afff
-- DevIconOrgMode xxx ctermfg=73 guifg=#77aa99
-- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
-- DevIconStorybookVue xxx ctermfg=204 guifg=#ff4785
-- DevIconKDEneon xxx ctermfg=37 guifg=#20a6a4
-- DevIconPyw     xxx ctermfg=39 guifg=#5aa7e4
-- DevIconStorybookTsx xxx ctermfg=204 guifg=#ff4785
-- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
-- DevIconStorybookTypeScript xxx ctermfg=204 guifg=#ff4785
-- DevIconStorybookSvelte xxx ctermfg=204 guifg=#ff4785
-- DevIconSwift   xxx ctermfg=166 guifg=#e37933
-- DevIconStorybookMjs xxx ctermfg=204 guifg=#ff4785
-- DevIconGentooBuild xxx ctermfg=60 guifg=#4c416e
-- DevIconStorybookJsx xxx ctermfg=204 guifg=#ff4785
-- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
-- DevIconStorybookJavaScript xxx ctermfg=204 guifg=#ff4785
-- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
-- DevIconKiCad   xxx ctermfg=231 guifg=#ffffff
-- DevIconTypoScript xxx ctermfg=208 guifg=#ff8700
-- DevIconSte     xxx ctermfg=101 guifg=#839463
-- DevIconGraphQL xxx ctermfg=199 guifg=#e535ab
-- DevIconHyprlandd xxx ctermfg=37 guifg=#00aaae
-- DevIconSecurity xxx ctermfg=251 guifg=#bec4c9
-- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
-- DevIconArch    xxx ctermfg=67 guifg=#0f94d2
-- DevIconPptx    xxx ctermfg=160 guifg=#cb4a32
-- DevIconOggSpeexAudio xxx ctermfg=24 guifg=#0075aa
-- DevIconPp      xxx ctermfg=214 guifg=#ffa61a
-- DevIconTypeScriptReactSpec xxx ctermfg=26 guifg=#1354bf
-- DevIconGIMP    xxx ctermfg=240 guifg=#635b46
-- DevIconSpecTs  xxx ctermfg=74 guifg=#519aba
-- DevIconBzl     xxx ctermfg=113 guifg=#89e051
-- DevIconJavaScriptReactSpec xxx ctermfg=45 guifg=#20c2e3
-- DevIconBackup  xxx ctermfg=66 guifg=#6d8086
-- DevIconSpecJs  xxx ctermfg=185 guifg=#cbcb41
-- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
-- DevIconQt      xxx ctermfg=77 guifg=#40cd52
-- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
-- DevIconVim     xxx ctermfg=28 guifg=#019833
-- DevIconSig     xxx ctermfg=166 guifg=#e37933
-- DevIconKsh     xxx ctermfg=240 guifg=#4d5a5e
-- DevIconPsScriptfile xxx ctermfg=68 guifg=#4273ca
-- DevIconSolveSpace xxx ctermfg=101 guifg=#839463
-- DevIconBicepParameters xxx ctermfg=133 guifg=#9f74b3
-- DevIconScalaScript xxx ctermfg=167 guifg=#cc3e44
-- DevIconXaml    xxx ctermfg=56 guifg=#512bd4
-- DevIconPyc     xxx ctermfg=222 guifg=#ffe291
-- DevIconSolidWorksPrt xxx ctermfg=101 guifg=#839463
-- DevIconGradleBuildScript xxx ctermfg=24 guifg=#005f87
-- DevIconSolidWorksAsm xxx ctermfg=101 guifg=#839463
-- DevIconGleam   xxx ctermfg=219 guifg=#ffaff3
-- DevIconSketchUp xxx ctermfg=101 guifg=#839463
-- DevIconErb     xxx ctermfg=52 guifg=#701516
-- DevIconFs      xxx ctermfg=74 guifg=#519aba
-- DevIconSha512  xxx ctermfg=103 guifg=#8c86af
-- DevIconXz      xxx ctermfg=214 guifg=#eca517
-- DevIconNswag   xxx ctermfg=112 guifg=#85ea2d
-- DevIconSln     xxx ctermfg=98 guifg=#854cc7
-- DevIconSha384  xxx ctermfg=103 guifg=#8c86af
-- DevIconPub     xxx ctermfg=222 guifg=#e3c58e
-- DevIconSha224  xxx ctermfg=103 guifg=#8c86af
-- DevIconSha1    xxx ctermfg=103 guifg=#8c86af
-- DevIconSublime xxx ctermfg=166 guifg=#e37933
-- DevIconTypeScriptReactTest xxx ctermfg=26 guifg=#1354bf
-- DevIconPy      xxx ctermfg=214 guifg=#ffbc03
-- DevIconGo      xxx ctermfg=38 guifg=#00add8
-- DevIconDll     xxx ctermfg=52 guifg=#4d2c0b
-- DevIconPl      xxx ctermfg=74 guifg=#519aba
-- DevIconObjectiveCPlusPlus xxx ctermfg=74 guifg=#519aba
-- DevIconToml    xxx ctermfg=124 guifg=#9c4221
-- DevIconAutoCADDwg xxx ctermfg=101 guifg=#839463
-- DevIconMd      xxx ctermfg=253 guifg=#dddddd
-- DevIconTor     xxx ctermfg=74 guifg=#519aba
-- DevIconGitCommit xxx ctermfg=196 guifg=#f54d27
-- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
-- DevIconSolidity xxx ctermfg=74 guifg=#519aba
-- DevIconObjectiveC xxx ctermfg=111 guifg=#599eff
-- DevIconJsx     xxx ctermfg=45 guifg=#20c2e3
-- DevIconPxi     xxx ctermfg=39 guifg=#5aa7e4
-- DevIconGitlabCI xxx ctermfg=196 guifg=#e24329
-- DevIconXfce    xxx ctermfg=74 guifg=#00aadf
-- DevIconLiquid  xxx ctermfg=106 guifg=#95bf47
-- DevIconYml     xxx ctermfg=66 guifg=#6d8086
-- DevIconIcs     xxx ctermfg=18 guifg=#2b2e83
-- DevIconConfiguration xxx ctermfg=66 guifg=#6d8086
-- DevIconStyl    xxx ctermfg=113 guifg=#8dc149
-- DevIconSml     xxx ctermfg=166 guifg=#e37933
-- DevIconMailmap xxx ctermfg=196 guifg=#f54d27
-- DevIconLibreOfficeGraphics xxx ctermfg=227 guifg=#fffb57
-- DevIconGoWork  xxx ctermfg=38 guifg=#00add8
-- DevIconIfc     xxx ctermfg=101 guifg=#839463
-- DevIconRar     xxx ctermfg=214 guifg=#eca517
-- DevIconIge     xxx ctermfg=101 guifg=#839463
-- DevIconPNPMFile xxx ctermfg=214 guifg=#f9ad02
-- DevIconTempl   xxx ctermfg=178 guifg=#dbbd30
-- DevIconTemplate xxx ctermfg=178 guifg=#dbbd30
-- DevIconPackageJson xxx ctermfg=197 guifg=#e8274b
-- DevIconGz      xxx ctermfg=214 guifg=#eca517
-- DevIconPreCommitConfig xxx ctermfg=214 guifg=#f8b424
-- DevIconSignature xxx ctermfg=166 guifg=#e37933
-- DevIconSway    xxx ctermfg=64 guifg=#68751c
-- DevIconAPL     xxx ctermfg=35 guifg=#24a148
-- DevIcondwm     xxx ctermfg=31 guifg=#1177aa
-- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
-- DevIconKritadisplayrc xxx ctermfg=201 guifg=#f245fb
-- DevIconFortran xxx ctermfg=97 guifg=#734f96
-- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
-- DevIconPrusaSlicer xxx ctermfg=202 guifg=#ec6b23
-- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
-- DevIconKDEPlasma xxx ctermfg=33 guifg=#1b89f4
-- DevIconZig     xxx ctermfg=172 guifg=#f69a1b
-- DevIconPuppyLinux xxx ctermfg=145 guifg=#a2aeb9
-- DevIconDiff    xxx ctermfg=239 guifg=#41535b
-- DevIconBuildTargets xxx ctermfg=75 guifg=#00a2ff
-- DevIconCentos  xxx ctermfg=132 guifg=#a2518d
-- DevIconOpenBSD xxx ctermfg=220 guifg=#f2ca30
-- DevIconSolus   xxx ctermfg=239 guifg=#4b5163
-- DevIconElementary xxx ctermfg=67 guifg=#5890c2
-- DevIconHyperbolaGNULinuxLibre xxx ctermfg=250 guifg=#c0c0c0
-- DevIconTrisquelGNULinux xxx ctermfg=25 guifg=#0f58b6
-- DevIconFreeCAD xxx ctermfg=160 guifg=#cb333b
-- DevIconZip     xxx ctermfg=214 guifg=#eca517
-- DevIconPop_OS  xxx ctermfg=73 guifg=#48b9c7
-- DevIconVHDL    xxx ctermfg=28 guifg=#019833
-- DevIconKali    xxx ctermfg=69 guifg=#2777ff
-- DevIconMobi    xxx ctermfg=215 guifg=#eab16d
-- DevIconFsi     xxx ctermfg=74 guifg=#519aba
-- DevIconPsScriptModulefile xxx ctermfg=68 guifg=#6975c4
-- DevIconMkv     xxx ctermfg=208 guifg=#fd971f
-- DevIconxmonad  xxx ctermfg=203 guifg=#fd4d5d
-- DevIconJs      xxx ctermfg=185 guifg=#cbcb41
-- DevIconGodotTextScene xxx ctermfg=66 guifg=#6d8086
-- DevIconCs      xxx ctermfg=58 guifg=#596706
-- DevIconPyx     xxx ctermfg=39 guifg=#5aa7e4
-- DevIconStp     xxx ctermfg=101 guifg=#839463
-- DevIconConda   xxx ctermfg=34 guifg=#43b02a
-- DevIconXDPH    xxx ctermfg=37 guifg=#00aaae
-- DevIconFeature xxx ctermfg=34 guifg=#00a818
-- DevIconJpegXl  xxx ctermfg=140 guifg=#a074c4
-- DevIconFsscript xxx ctermfg=74 guifg=#519aba
-- DevIconXorgConf xxx ctermfg=196 guifg=#e54d18
-- DevIconThunderbird xxx ctermfg=33 guifg=#137be1
-- DevIconVertexShader xxx ctermfg=67 guifg=#5586a6
-- DevIconapk     xxx ctermfg=35 guifg=#34a853
-- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
-- DevIconKbx     xxx ctermfg=243 guifg=#737672
-- DevIconRasi    xxx ctermfg=185 guifg=#cbcb41
-- DevIconIllumos xxx ctermfg=196 guifg=#ff430f
-- DevIconFragmentShader xxx ctermfg=67 guifg=#5586a6
-- DevIconAudioInterchangeFileFormat xxx ctermfg=39 guifg=#00afff
-- DevIconSha256  xxx ctermfg=103 guifg=#8c86af
-- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
-- DevIconCSharpProject xxx ctermfg=56 guifg=#512bd4
-- DevIconEnlightenment xxx ctermfg=231 guifg=#ffffff
-- DevIconHurl    xxx ctermfg=198 guifg=#ff0288
-- DevIconAdvancedAudioCoding xxx ctermfg=39 guifg=#00afff
-- DevIconAutoCADDxf xxx ctermfg=101 guifg=#839463
-- DevIcon3gp     xxx ctermfg=208 guifg=#fd971f
-- DevIconKdenlive xxx ctermfg=110 guifg=#83b8f2
-- DevIconSlim    xxx ctermfg=196 guifg=#e34c26
-- DevIconSlnx    xxx ctermfg=98 guifg=#854cc7
-- DevIconScss    xxx ctermfg=204 guifg=#f55385
-- DevIconPls     xxx ctermfg=211 guifg=#ed95ae
-- DevIconDesktopEntry xxx ctermfg=54 guifg=#563d7c
-- DevIconSvelteConfig xxx ctermfg=196 guifg=#ff3e00
-- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
-- DevIconScheme  xxx ctermfg=255 guifg=#eeeeee
-- DevIconGradleSettings xxx ctermfg=24 guifg=#005f87
-- DevIconZorin   xxx ctermfg=39 guifg=#14a1e8
-- DevIconSass    xxx ctermfg=204 guifg=#f55385
-- DevIconXeroLinux xxx ctermfg=104 guifg=#888fe2
-- DevIconawesome xxx ctermfg=59 guifg=#535d6c
-- DevIconRs      xxx ctermfg=216 guifg=#dea584
-- DevIconRake    xxx ctermfg=52 guifg=#701516
-- DevIconGemspec xxx ctermfg=52 guifg=#701516
-- DevIconOdin    xxx ctermfg=32 guifg=#3882d2
-- DevIconPy.typed xxx ctermfg=214 guifg=#ffbc03
-- DevIconObjectFile xxx ctermfg=124 guifg=#9f0500
-- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
-- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
-- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
-- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
-- DevIconCp      xxx ctermfg=74 guifg=#519aba
-- DevIconJl      xxx ctermfg=133 guifg=#a270ba
-- DevIconGTK     xxx ctermfg=231 guifg=#ffffff
-- DevIconAvif    xxx ctermfg=140 guifg=#a074c4
-- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
-- DevIconWebm    xxx ctermfg=208 guifg=#fd971f
-- DevIconWebpack xxx ctermfg=74 guifg=#519aba
-- DevIconXls     xxx ctermfg=29 guifg=#207245
-- DevIconOpenTypeFont xxx ctermfg=255 guifg=#ececec
-- DevIconXlsx    xxx ctermfg=29 guifg=#207245
-- DevIconXcPlayground xxx ctermfg=166 guifg=#e37933
-- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
-- DevIconWasm    xxx ctermfg=62 guifg=#5c4cdb
-- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
-- DevIconNotebook xxx ctermfg=208 guifg=#f57d01
-- DevIconBlender xxx ctermfg=208 guifg=#ea7600
-- DevIconRproj   xxx ctermfg=29 guifg=#358a5b
-- DevIconPyo     xxx ctermfg=222 guifg=#ffe291
-- DevIconPyd     xxx ctermfg=222 guifg=#ffe291
-- DevIconAppleScript xxx ctermfg=66 guifg=#6d8085
-- DevIconPsd     xxx ctermfg=74 guifg=#519aba
-- DevIconPsb     xxx ctermfg=74 guifg=#519aba
-- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
-- DevIconPpt     xxx ctermfg=160 guifg=#cb4a32
-- DevIconPng     xxx ctermfg=140 guifg=#a074c4
-- DevIconReScriptInterface xxx ctermfg=204 guifg=#f55385
-- DevIconHyprland xxx ctermfg=37 guifg=#00aaae
-- DevIconOpusAudioFile xxx ctermfg=24 guifg=#0075aa
-- DevIconEslintrc xxx ctermfg=56 guifg=#4b32c3
-- DevIconReScript xxx ctermfg=167 guifg=#cc3e44
-- DevIconCjs     xxx ctermfg=185 guifg=#cbcb41
-- DevIconAdaSpecification xxx ctermfg=140 guifg=#a074c4
-- DevIconGCode   xxx ctermfg=32 guifg=#1471ad
-- DevIconAndroid xxx ctermfg=35 guifg=#34a853
-- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
-- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
-- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
-- DevIconVitestConfig xxx ctermfg=106 guifg=#739b1b
-- DevIconC       xxx ctermfg=111 guifg=#599eff
-- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
-- DevIconBinaryGLTF xxx ctermfg=214 guifg=#ffb13b
-- DevIconGif     xxx ctermfg=140 guifg=#a074c4
-- DevIconGemfile xxx ctermfg=52 guifg=#701516
-- DevIconMustache xxx ctermfg=166 guifg=#e37933
-- DevIconLXQtConfigFile xxx ctermfg=32 guifg=#0192d3
-- DevIconFIGletFontFormat xxx ctermfg=255 guifg=#ececec
-- DevIconFIGletFontControl xxx ctermfg=255 guifg=#ececec
-- DevIconLXDEConfigFile xxx ctermfg=246 guifg=#909090
-- DevIconFreeLosslessAudioCodec xxx ctermfg=24 guifg=#0075aa
-- DevIconTypoScriptSetup xxx ctermfg=208 guifg=#ff8700
-- DevIconNobaraLinux xxx ctermfg=231 guifg=#ffffff
-- DevIconKritarc xxx ctermfg=201 guifg=#f245fb
-- DevIconNixOS   xxx ctermfg=110 guifg=#7ab1db
-- DevIconFdmdownload xxx ctermfg=43 guifg=#44cda8
-- DevIconKrita   xxx ctermfg=201 guifg=#f245fb
-- DevIconMXLinux xxx ctermfg=231 guifg=#ffffff
-- DevIconMPEG4   xxx ctermfg=39 guifg=#00afff
-- DevIconMp4     xxx ctermfg=208 guifg=#fd971f
-- DevIconMPEGAudioLayerIII xxx ctermfg=39 guifg=#00afff
-- DevIconMageia  xxx ctermfg=67 guifg=#2397d4
-- DevIconMOV     xxx ctermfg=208 guifg=#fd971f
-- DevIconPxd     xxx ctermfg=39 guifg=#5aa7e4
-- DevIconKalgebrarc xxx ctermfg=32 guifg=#1c99f3
-- DevIconLXLE    xxx ctermfg=238 guifg=#474747
-- DevIconFusion360 xxx ctermfg=101 guifg=#839463
-- DevIconIonic   xxx ctermfg=33 guifg=#4f8ff7
-- DevIconGradleProperties xxx ctermfg=24 guifg=#005f87
-- DevIconLocOS   xxx ctermfg=214 guifg=#fab402
-- DevIconHaxe    xxx ctermfg=208 guifg=#ea8220
-- DevIconIndexTheme xxx ctermfg=35 guifg=#2db96f
-- DevIconVlang   xxx ctermfg=67 guifg=#5d87bf
-- DevIconXSettingsdConf xxx ctermfg=196 guifg=#e54d18
-- DevIconEpub    xxx ctermfg=215 guifg=#eab16d
-- DevIconi3      xxx ctermfg=255 guifg=#e8ebee
-- DevIconLeap    xxx ctermfg=221 guifg=#fbc75d
-- DevIconEmbeddedOpenTypeFont xxx ctermfg=255 guifg=#ececec
-- DevIconKubuntu xxx ctermfg=32 guifg=#007ac2
-- DevIconGradleWrapperProperties xxx ctermfg=24 guifg=#005f87
-- DevIconMts     xxx ctermfg=74 guifg=#519aba
-- DevIconTwig    xxx ctermfg=113 guifg=#8dc149
-- DevIconKiCadCache xxx ctermfg=231 guifg=#ffffff
-- DevIconInfo    xxx ctermfg=230 guifg=#ffffcd
-- DevIconWranglerConfig xxx ctermfg=208 guifg=#f48120
-- DevIconJWM     xxx ctermfg=32 guifg=#0078cd
-- DevIconFluxbox xxx ctermfg=240 guifg=#555555
-- DevIconMagnet  xxx ctermfg=124 guifg=#a51b16
-- DevIconTypeScriptDeclaration xxx ctermfg=172 guifg=#d59855
-- DevIconEbook   xxx ctermfg=215 guifg=#eab16d
-- DevIconM4V     xxx ctermfg=208 guifg=#fd971f
-- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
-- DevIconGuix    xxx ctermfg=220 guifg=#ffcc00
-- DevIconGruntfile xxx ctermfg=166 guifg=#e37933
-- DevIconM3u     xxx ctermfg=211 guifg=#ed95ae
-- DevIconVLC     xxx ctermfg=208 guifg=#ee7a00
-- DevIconGentoo  xxx ctermfg=146 guifg=#b1abce
-- DevIconKiCadFootprintTable xxx ctermfg=231 guifg=#ffffff
-- DevIconTFVars  xxx ctermfg=93 guifg=#5f43e9
-- DevIconNextConfigTs xxx ctermfg=231 guifg=#ffffff
-- DevIconGradleWrapperScript xxx ctermfg=24 guifg=#005f87
-- DevIconVercel  xxx ctermfg=231 guifg=#ffffff
-- DevIconDconf   xxx ctermfg=231 guifg=#ffffff
-- DevIconLibrecadFontFile xxx ctermfg=255 guifg=#ececec
-- DevIconPlatformio xxx ctermfg=208 guifg=#f6822b
-- DevIconGoMod   xxx ctermfg=38 guifg=#00add8
-- DevIconRb      xxx ctermfg=52 guifg=#701516
-- DevIconTSConfig xxx ctermfg=74 guifg=#519aba
-- DevIconLock    xxx ctermfg=250 guifg=#bbbbbb
-- DevIconHbs     xxx ctermfg=202 guifg=#f0772b
-- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
-- DevIconHaml    xxx ctermfg=255 guifg=#eaeae1
-- DevIconDockerIgnore xxx ctermfg=68 guifg=#458ee6
-- DevIconTailwindConfig xxx ctermfg=45 guifg=#20c2e3
-- DevIconLinuxKernelObject xxx ctermfg=253 guifg=#dcddd6
-- DevIconKiCadSymbolTable xxx ctermfg=231 guifg=#ffffff
-- DevIconBat     xxx ctermfg=191 guifg=#c1f12e
-- DevIconCrdownload xxx ctermfg=43 guifg=#44cda8
-- DevIconVerilog xxx ctermfg=28 guifg=#019833
-- DevIconCommitlintConfig xxx ctermfg=30 guifg=#2b9689
-- DevIconHTTP    xxx ctermfg=31 guifg=#008ec7
-- DevIconKdb     xxx ctermfg=71 guifg=#529b34
-- DevIconGeometryShader xxx ctermfg=67 guifg=#5586a6
-- DevIconCowsayFile xxx ctermfg=130 guifg=#965824
-- DevIconcuda    xxx ctermfg=113 guifg=#89e051
-- DevIconQtile   xxx ctermfg=231 guifg=#ffffff
-- DevIconCodeOfConduct xxx ctermfg=161 guifg=#e41662
-- DevIconConfigRu xxx ctermfg=52 guifg=#701516
-- DevIconDoc     xxx ctermfg=26 guifg=#185abd
-- DevIconCMakeLists xxx ctermfg=254 guifg=#dce3eb
-- DevIconCts     xxx ctermfg=74 guifg=#519aba
-- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
-- DevIconGodotTextResource xxx ctermfg=66 guifg=#6d8086
-- DevIconClojureDart xxx ctermfg=74 guifg=#519aba
-- DevIconMotoko  xxx ctermfg=135 guifg=#9772fb
-- DevIconCantorrc xxx ctermfg=32 guifg=#1c99f3
-- DevIconPsManifestfile xxx ctermfg=68 guifg=#6975c4
-- DevIconFsx     xxx ctermfg=74 guifg=#519aba
-- DevIconAss     xxx ctermfg=214 guifg=#ffb713
-- DevIconSsa     xxx ctermfg=214 guifg=#ffb713
-- DevIconSrt     xxx ctermfg=214 guifg=#ffb713
-- DevIconJar     xxx ctermfg=215 guifg=#ffaf67
-- DevIconManjaro xxx ctermfg=35 guifg=#33b959
-- DevIconKdenliverc xxx ctermfg=110 guifg=#83b8f2
-- DevIconNextConfigCjs xxx ctermfg=231 guifg=#ffffff
-- DevIconDot     xxx ctermfg=24 guifg=#30638e
-- DevIconClojureC xxx ctermfg=113 guifg=#8dc149
-- DevIconBz3     xxx ctermfg=214 guifg=#eca517
-- DevIconKdenliveLayoutsrc xxx ctermfg=110 guifg=#83b8f2
-- DevIconBz2     xxx ctermfg=214 guifg=#eca517
-- DevIconVanillaOS xxx ctermfg=214 guifg=#fabd4d
-- DevIconBz      xxx ctermfg=214 guifg=#eca517
-- DevIconCsv     xxx ctermfg=113 guifg=#89e051
-- DevIconBoundaryRepresentation xxx ctermfg=101 guifg=#839463
-- DevIconDart    xxx ctermfg=25 guifg=#03589c
-- DevIconImg     xxx ctermfg=181 guifg=#d0bec8
-- DevIconMdx     xxx ctermfg=74 guifg=#519aba
-- DevIconImage   xxx ctermfg=181 guifg=#d0bec8
-- DevIconSabayon xxx ctermfg=251 guifg=#c6c6c6
-- DevIconIgs     xxx ctermfg=101 guifg=#839463
-- DevIconNano    xxx ctermfg=54 guifg=#440077
-- DevIconIges    xxx ctermfg=101 guifg=#839463
-- DevIconGPRBuildProject xxx ctermfg=66 guifg=#6d8086
-- DevIconLabView xxx ctermfg=220 guifg=#fec60a
-- DevIconRaspberryPiOS xxx ctermfg=161 guifg=#be1848
-- DevIconBlade   xxx ctermfg=203 guifg=#f05340
-- DevIconIfb     xxx ctermfg=18 guifg=#2b2e83
-- DevIconRockyLinux xxx ctermfg=36 guifg=#0fb37d
-- DevIconTumbleweed xxx ctermfg=37 guifg=#35b9ab
-- DevIconLib     xxx ctermfg=52 guifg=#4d2c0b
-- DevIconRakefile xxx ctermfg=52 guifg=#701516
-- DevIconStep    xxx ctermfg=101 guifg=#839463
-- DevIconIcalendar xxx ctermfg=18 guifg=#2b2e83
-- DevIconWeston  xxx ctermfg=214 guifg=#ffbb01
-- DevIconIcal    xxx ctermfg=18 guifg=#2b2e83
-- DevIconClojure xxx ctermfg=113 guifg=#8dc149
-- DevIconAzureCli xxx ctermfg=32 guifg=#0078d4
-- DevIconTxz     xxx ctermfg=214 guifg=#eca517
-- DevIconDocx    xxx ctermfg=26 guifg=#185abd
-- DevIconHuff    xxx ctermfg=56 guifg=#4242c7
-- DevIconLibreOfficeWriter xxx ctermfg=81 guifg=#2dcbfd
-- DevIconMojo    xxx ctermfg=196 guifg=#ff4c1f
-- DevIconTrueTypeFont xxx ctermfg=255 guifg=#ececec
-- DevIconUI      xxx ctermfg=27 guifg=#015bf0
-- DevIconEpp     xxx ctermfg=214 guifg=#ffa61a
-- DevIconWindows xxx ctermfg=39 guifg=#00a4ef
-- DevIconTypoScriptConfig xxx ctermfg=208 guifg=#ff8700
-- DevIconRobotsTxt xxx ctermfg=60 guifg=#5d7096
-- DevIconNorg    xxx ctermfg=32 guifg=#4878be
-- DevIconBibTeX  xxx ctermfg=185 guifg=#cbcb41
-- DevIconParrot  xxx ctermfg=45 guifg=#54deff
-- DevIconColdFusionTag xxx ctermfg=38 guifg=#01a4ba
-- DevIconColdFusionScript xxx ctermfg=38 guifg=#01a4ba
-- DevIconBash    xxx ctermfg=113 guifg=#89e051
-- DevIconLuacheckrc xxx ctermfg=75 guifg=#00a2ff
-- DevIconKdbx    xxx ctermfg=71 guifg=#529b34
-- DevIconZst     xxx ctermfg=214 guifg=#eca517
-- DevIconAdaBody xxx ctermfg=111 guifg=#599eff
-- DevIconPrisma  xxx ctermfg=62 guifg=#5a67d8
-- DevIconMint    xxx ctermfg=108 guifg=#87c095
-- DevIconMd5     xxx ctermfg=103 guifg=#8c86af
-- DevIconMpv     xxx ctermfg=53 guifg=#3b1342
-- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
-- DevIconWavPack xxx ctermfg=39 guifg=#00afff
-- DevIconMaven   xxx ctermfg=52 guifg=#7a0d21
-- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
-- DevIconJustfile xxx ctermfg=66 guifg=#6d8086
-- DevIconXpi     xxx ctermfg=196 guifg=#ff1b01
-- DevIconriver   xxx ctermfg=16 guifg=#000000
-- DevIconPm      xxx ctermfg=74 guifg=#519aba
-- DevIconMATE    xxx ctermfg=113 guifg=#9bda5c
-- DevIconLuaurc  xxx ctermfg=75 guifg=#00a2ff
-- DevIconGradle  xxx ctermfg=24 guifg=#005f87
-- DevIconEslintIgnore xxx ctermfg=56 guifg=#4b32c3
-- DevIconHyprsunset xxx ctermfg=37 guifg=#00aaae
-- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
-- DevIconDevuan  xxx ctermfg=238 guifg=#404a52
-- DevIconJenkins xxx ctermfg=160 guifg=#d33833
-- DevIconnode    xxx ctermfg=71 guifg=#5fa04e
-- DevIconKDEglobals xxx ctermfg=32 guifg=#1c99f3
-- DevIconOpenSCAD xxx ctermfg=220 guifg=#f9d72c
-- DevIconFish    xxx ctermfg=240 guifg=#4d5a5e
-- DevIconOut     xxx ctermfg=124 guifg=#9f0500
-- DevIconFsharp  xxx ctermfg=74 guifg=#519aba
-- DevIconWebmanifest xxx ctermfg=185 guifg=#f1e05a
-- DevIconGitAttributes xxx ctermfg=196 guifg=#f54d27
-- DevIconGitModules xxx ctermfg=196 guifg=#f54d27
-- DevIconMli     xxx ctermfg=166 guifg=#e37933
-- DevIconGitConfig xxx ctermfg=196 guifg=#f54d27
-- DevIconXauthority xxx ctermfg=196 guifg=#e54d18
-- DevIconSRCINFO xxx ctermfg=67 guifg=#0f94d2
-- DevIconXresources xxx ctermfg=196 guifg=#e54d18
-- DevIconQuery   xxx ctermfg=107 guifg=#90a850
-- DevIconBuildProps xxx ctermfg=75 guifg=#00a2ff
-- DevIconPKGBUILD xxx ctermfg=67 guifg=#0f94d2
-- DevIconPackagesProps xxx ctermfg=75 guifg=#00a2ff
-- DevIconAUTHORS xxx ctermfg=135 guifg=#a172ff
-- DevIconFreeCADConfig xxx ctermfg=160 guifg=#cb333b
-- DevIconHyprpaper xxx ctermfg=37 guifg=#00aaae
-- DevIconConf    xxx ctermfg=66 guifg=#6d8086
-- DevIconD       xxx ctermfg=124 guifg=#b03931
-- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
-- DevIconVala    xxx ctermfg=91 guifg=#7b3db9
-- DevIconHtml    xxx ctermfg=196 guifg=#e44d26
-- DevIconMjs     xxx ctermfg=185 guifg=#f1e05a
-- DevIconMarkdown xxx ctermfg=253 guifg=#dddddd
-- lualine_x_filetype_DevIconCpp_normal xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_x_filetype_DevIconCpp_insert xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_x_filetype_DevIconCpp_visual xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_x_filetype_DevIconCpp_replace xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_x_filetype_DevIconCpp_command xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_x_filetype_DevIconCpp_terminal xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_x_filetype_DevIconCpp_inactive xxx gui=nocombine guifg=#c0a3a5 guibg=#34383d
-- lualine_transitional_lualine_a_normal_to_lualine_b_branch_normal xxx gui=nocombine guifg=#87aab5 guibg=#34383d
-- lualine_transitional_lualine_a_normal_to_lualine_b_normal xxx gui=nocombine guifg=#87aab5 guibg=#34383d
-- BlinkCmpLabelDetail xxx links to PmenuExtra
-- BlinkCmpLabelDescription xxx links to PmenuExtra
-- BlinkCmpSource xxx links to PmenuExtra
-- BlinkCmpKind   xxx links to PmenuKind
-- BlinkCmpScrollBarThumb xxx links to PmenuThumb
-- BlinkCmpScrollBarGutter xxx links to PmenuSbar
-- BlinkCmpMenuSelection xxx links to PmenuSel
-- BlinkCmpDoc    xxx links to NormalFloat
-- BlinkCmpDocSeparator xxx links to NormalFloat
-- BlinkCmpDocCursorLine xxx links to Visual
-- BlinkCmpSignatureHelp xxx links to NormalFloat
-- BlinkCmpSignatureHelpActiveParameter xxx links to LspSignatureActiveParameter
-- FidgetNoBlend  xxx cleared
-- lualine_transitional_lualine_a_command_to_lualine_b_branch_command xxx gui=nocombine guifg=#bc9a9c guibg=#34383d
-- lualine_transitional_lualine_a_command_to_lualine_b_command xxx gui=nocombine guifg=#bc9a9c guibg=#34383d
-- lualine_transitional_lualine_a_insert_to_lualine_b_branch_insert xxx gui=nocombine guifg=#9da380 guibg=#34383d
-- lualine_transitional_lualine_a_insert_to_lualine_b_insert xxx gui=nocombine guifg=#9da380 guibg=#34383d
-- BlinkCmpCursorLineMenuHack xxx guibg=#51575d
